### ISSUE TITLE
pjax下，isso、crossover、gitalk、vssue 评论系统无法加载

### ISSUE THREAD

**Issue by BeiyanYunyi** [xaoxuu/hexo-theme-volantis#452]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

pjax启用时，单击任意位置的文章链接进入任意新文章均不加载评论系统，必须刷新页面才有。  
不确定 gitalk 等评论系统是否也存在同样的问题，但就我先前在另一个主题（Hexo-theme-Sakura）上移植 gitalk 和 vssue 时的结果来看，它们同样不支持pjax。  
（看了 issues 好像只有对 LeanCloud 系评论服务不支持 pjax 的反馈，所以我这里丢个 issue 出来）  
目前我的解决方案只有暂时在 pjax url 里 ban 掉评论系统的 url。  
需要测试的话我可以提供我 isso 和 crossover 的后端地址出来。  
明明 isso 和 crossover 的相关代码都是我提交的，没能力解决真的丢人（捂脸）
### 复现地址

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

</details>

### 浏览器、操作系统
Mozilla Firefox Beta / Stable均存在问题。  
操作系统：Windows 和 Linux（Archlinux）均存在问题。

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```
v14.7.0  
6.14.7
#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by inkss** [comment]
gitalk 应该是做过兼容，另外三确认压根没处理
