### ISSUE TITLE
离开标签页时暂停 Parallax

### ISSUE THREAD

**Issue by inkss** [xaoxuu/hexo-theme-volantis#672]
## 需求描述

rt

## 参考链接

https://github.com/wagerfield/parallax#disable

**Comment by MHuiG** [comment]
暂停这个定时器?

https://github.com/volantis-x/hexo-theme-volantis/blob/36221f46fc98604698dea2683a1d8ec4a763bbfd/layout/_plugins/parallax/script.ejs#L31-L34

**Comment by MHuiG** [comment]
没有封面的时候 Parallax 是 return 出去的

https://github.com/volantis-x/hexo-theme-volantis/blob/36221f46fc98604698dea2683a1d8ec4a763bbfd/layout/_plugins/parallax/script.ejs#L42-L44

**Comment by inkss** [comment]
比如说文档站，切换到其他标签页了，然后过了一段时间后再切回来后背景一通切换。

**Comment by MHuiG** [comment]
不知道是哪里的问题 (会不会是pjax

**Comment by MHuiG** [comment]
话说这个页面的报错是什么鬼 https://volantis.js.org/examples/
