### ISSUE TITLE
缺少 Google.svg 文件

### ISSUE THREAD

**Issue by 1an8r0wn** [xaoxuu/hexo-theme-volantis#678]
当搜索设置为 Google CSE 的时候，搜索框中缺少了 Google.svg 文件。

对应CDN 为 https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@master/img/logo/，经查，上面缺少了 Google.svg

对应主题文件是：_blog/volantis/source/js/search/google.js
对应行：line 40

**Comment by inkss** [comment]
v5 版本移除了除 hexo 外的所有搜索  😂😂😂

**Comment by xaoxuu** [comment]
我记得你用过agolia，现在连那个也删了？

**Comment by inkss** [comment]
mhuig 重构了搜索

**Comment by inkss** [comment]
> 原 google, algolia, azure, baidu 站内搜索 系祖传代码, 且文档丢失, 不便后续维护 在 5.0 版本移除
