### ISSUE TITLE
开启scrollreveal后会导致文章随机加载不全

### ISSUE THREAD

**Issue by zryyyy** [xaoxuu/hexo-theme-volantis#680]
将scrollreveal设置为true后，首页文章有时候会加载但是有时候不会加载，将true加上注释后就不会出现问题

**Comment by inkss** [comment]
可能是滑动距离的问题，有复现链接吗

**Comment by zryyyy** [comment]
> 可能是滑动距离的问题，有复现链接吗

啊这...没有复现链接，，，我后来发现出现问题频率不低然后就关了
我开了scrollreveal以后如果滑动很快就有很大概率造成首页的文章卡片加载不全
