### ISSUE TITLE
scroll_smooth 开启平滑滚动导致页面卡死奔溃

### ISSUE THREAD

**Issue by cltsp** [xaoxuu/hexo-theme-volantis#692]
## 预期与实际表现的区别

scroll_smooth 开启平滑滚动导致页面卡死奔溃

## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。您当前使用的volantis版本为：5.0.0-alpha.5
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. 在文章页面，切换目录，只要稍微频繁一点就能复现
2. 后面有性能分析报告，主线程被长时间阻塞，页面无响应

### 复现地址：

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图:</summary>

![image](https://user-images.githubusercontent.com/10330716/144753526-23f3bc57-ce08-4198-99fd-adacf89351e1.png)

</details>

### 浏览器、操作系统
Firefox 94.0.2、Chrome 96.0.4664.55 都能复现该问题
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
@MHuiG 这段代码造成的问题，Chrome 是不是最近更新了什么，我在 Edge 上没复现。

https://github.com/volantis-x/hexo-theme-volantis/blob/e44eca1c1743573f58131883e1aa6534aaf476c2/layout/_partial/scripts/global.ejs#L339-L348

**Comment by MHuiG** [comment]
复现不出来

https://user-images.githubusercontent.com/38281581/144797845-a436a233-219d-49c2-9046-3dec5d57d0cf.mp4

**Comment by cltsp** [comment]
https://user-images.githubusercontent.com/10330716/144802456-1d77f74e-c380-488d-baec-f9a0631c2757.mov

**Comment by cltsp** [comment]
> 复现不出来
> 
>  SVID_20211206_142351_1.mp4
你这是 移动端的 Chrome ？我是 Mac Os 11.5.2、Windows PC 上的 Chrome 貌似也能复现。

**Comment by cltsp** [comment]
https://user-images.githubusercontent.com/10330716/144804007-fa119b53-7edf-4d2e-97d8-3a20417a0979.mov
<img width="1680" alt="截屏2021-12-06 下午3 15 48" src="https://user-images.githubusercontent.com/10330716/144804027-05fa068c-2695-4234-8c8f-ffc85ea25909.png">



<blockquote></blockquote>

**Comment by inkss** [comment]
@MHuiG 要不然还是把那个判断关掉得了

https://pan.adc.ink/w4j1e/2021-12-06-15-17-10_x264.mp4?preview

**Comment by MHuiG** [comment]
要不直接去掉目录定位的平滑滚动效果？

https://github.com/volantis-x/hexo-theme-volantis/issues/476#issue-693959157

**Comment by inkss** [comment]
> 要不直接去掉目录定位的平滑滚动效果？
> 
> [#476 (comment)](https://github.com/volantis-x/hexo-theme-volantis/issues/476#issue-693959157)

平滑滚动还是留着吧，我自己用的那个，好像一开始就改成了 false，也没太发现定位不准。

https://github.com/inkss/volantis/blob/cae0ef39160c47854c76c8aae45a3452b527f09a/layout/_partial/scripts/toc.ejs#L18

<blockquote><img src="https://opengraph.githubassets.com/83d0c3abc56284d568602a42a16bc6e3af690f99d172856e0f026f1ec986da3b/inkss/volantis" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/inkss/volantis">volantis/toc.ejs at cae0ef39160c47854c76c8aae45a3452b527f09a · inkss/volantis</a></strong></div><div>基于 volantis 的个人修改~. Contribute to inkss/volantis development by creating an account on GitHub.</div></blockquote>

**Comment by MHuiG** [comment]
> > 要不直接去掉目录定位的平滑滚动效果？
> > [#476 (comment)](https://github.com/volantis-x/hexo-theme-volantis/issues/476#issue-693959157)
> 
> 平滑滚动还是留着吧，我自己用的那个，好像一开始就改成了 false，也没太发现定位不准。
> 
> https://github.com/inkss/volantis/blob/cae0ef39160c47854c76c8aae45a3452b527f09a/layout/_partial/scripts/toc.ejs#L18
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f3bddb5e714ff0c4c3590ebba1eb981068a664da2e7102f60d6f49b29dd24d7a/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f383364306333616263353632383464353638363032613432613136626336653361663639306639396431373238353665306630323666316563393836646133622f696e6b73732f766f6c616e746973"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[volantis/toc.ejs at cae0ef39160c47854c76c8aae45a3452b527f09a · inkss/volantis](https://github.com/inkss/volantis)**基于 volantis 的个人修改~. Contribute to inkss/volantis development by creating an account on GitHub.

这一段当时是用来修正图片懒加载错位用的

那先改FALSE吧

<blockquote><img src="https://opengraph.githubassets.com/83d0c3abc56284d568602a42a16bc6e3af690f99d172856e0f026f1ec986da3b/inkss/volantis" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/inkss/volantis">volantis/toc.ejs at cae0ef39160c47854c76c8aae45a3452b527f09a · inkss/volantis</a></strong></div><div>基于 volantis 的个人修改~. Contribute to inkss/volantis development by creating an account on GitHub.</div></blockquote>

**Comment by inkss** [comment]
没停

![Snipaste_21-12-06_15-58-11](https://user-images.githubusercontent.com/31947043/144808783-eb251a1c-2d69-4181-8f3d-314f99fb530b.png)

**Comment by MHuiG** [comment]
也许在点击下一个toc时应该事先把事件list置空

volantis.scroll.unengine.list＝[]

**Comment by inkss** [comment]
edge 和 chrome，在 requestAnimationFrame 的应用上不一样了

**Comment by inkss** [comment]
@MHuiG 那个检测估计得重新写了，感觉得节流一下

**Comment by xaoxuu** [comment]
建议直接砍掉

**Comment by MHuiG** [comment]
建议直接砍掉平滑滚动
