### ISSUE TITLE
开启scrollreveal后会随机导致文章列表末尾部分丢失

### ISSUE THREAD

**Issue by cltsp** [xaoxuu/hexo-theme-volantis#693]
## 如何复现这个问题

- [ ] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。您当前使用的volantis版本为：5.0.0-alpha.5
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. 开启scrollreveal配置，快速滚动、偶尔无法看到末尾文章列表、详情见截图
2. 关闭scrollreveal无此现象

### 复现地址：

- [x] 文档官网源码本地运行存在异常。
- [] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 

### 截图

<details><summary>相关截图:</summary>
![image](https://user-images.githubusercontent.com/10330716/144814364-16512581-986d-4730-a356-aaf4bfd6c0fc.png)

![image](https://user-images.githubusercontent.com/10330716/144814344-2917ff51-41ff-4a4f-9603-ab614580bf28.png)

</details>

### 浏览器、操作系统
MacOs 、Chrome 
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by cltsp** [comment]
![image](https://user-images.githubusercontent.com/10330716/144815097-6c9e71b9-0b6b-4bcd-bec7-06cd40ba3731.png)

**Comment by cltsp** [comment]
初步判断是这段代码导致的，注释了就好了
![image](https://user-images.githubusercontent.com/10330716/144990271-b1dd483f-3ac1-4912-b498-54c50050ddf6.png)

**Comment by inkss** [comment]
scrollreveal 开启时关闭此段
