### ISSUE TITLE
文章目录是否可以全局显示呢？

### ISSUE THREAD

**Issue by gzldc** [xaoxuu/hexo-theme-volantis#694]
## 需求描述：

文章目录是否可以全局显示，类似[mybatis-plus的文档说明](https://mp.baomidou.com/guide/)。
如果系统限制无法做到类似效果的话，是否支持配置目录显示位置呢？
就是把目录展示在文章左侧。（默认是右侧）

## 参考链接
https://mp.baomidou.com/guide/

**Comment by inkss** [comment]
你可以试试 @xaoxuu 的 [hexo-theme-stellar](https://github.com/xaoxuu/hexo-theme-stellar)。

**Comment by gzldc** [comment]
给

> 你可以试试 @xaoxuu 的 [hexo-theme-stellar](https://github.com/xaoxuu/hexo-theme-stellar)。

感谢！

**Comment by inkss** [comment]
注：这个主题不太适合全局的目录显示
