### ISSUE TITLE
使用官网的配置示例,封面轮播图没显示

### ISSUE THREAD

**Issue by lovelyJason** [xaoxuu/hexo-theme-volantis#695]
环境: volantis  main分支最新代码

_config.valantis.yml
```
plugins:
  comment_typing: false
  # backstretch:
  # #   enable: false
  #   position: fixed
  #   images:             # For personal use only. At your own risk if used for commercial purposes !!!
  #     - https://cdn.jsdelivr.net/gh/lovelyJason/cdn-gallery/scenic/4456776-3705836a00587303.jpeg
  parallax:
    enable: #true
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 10000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/lovelyJason/cdn-gallery/scenic/4456776-3705836a00587303.jpeg
      - https://cdn.jsdelivr.net/gh/lovelyJason/cdn-gallery/scenic/4456776-3705836a00587303.jpeg
```

设置了position: fixed才会显示出来背景图?我检查了下页面元素, 当设置为cover时,这个样式设置为了隐藏,导致cover没有出现,图片也没加载,为什么?
```
<div id="none" class="cover-wrapper  dock" style=" display: none; ">...</div>
```
------
我调试了下代码,发现layout/_partial/scripts/_ctrl/coverCtr.ejs有以下代码被执行
```javascript
<%_
  // 为保证初次进入页面流畅，要求开启pjax且浏览器禁用Javascript时(仅HTML渲染)封面控制正常
  // layout/_plugins/pjax/pdata.ejs
  // layout/_partial/cover.ejs
  // layout/_partial/header.ejs
  theme.pjax_cover={}
  theme.pjax_cover.enableCover = false; // 封面是否开启
  theme.pjax_cover.frontMatterCover = 'none';  // 封面控制
  theme.pjax_cover.coverWrapperDisplay = 'none';
  theme.pjax_cover.scrollDownDisplay = 'none';
...
```

而layout/_partial/cover.ejs中对cover-wrapper的描述是
```ejs
<div id="<%- theme.pjax_cover.frontMatterCover %>" class='cover-wrapper <%- page.layout %> <%- theme.cover.layout_scheme %>' style="display: <%- theme.pjax_cover.coverWrapperDisplay %>;">

```

这里给他display设置了为none为什么?还是说我有什么参数漏配了?

**Comment by lovelyJason** [comment]
帮帮我

**Comment by inkss** [comment]
看到你这个仓库 [qdovo](https://github.com/lovelyJason/qdovo) 引用的主题是基 0ec50565261113830406c01b3dc0f5d4b0266775 这版拉取的，和主题主分支落后很远了。

不过如果是主题的 main（ df017f95a7b854b2a91e86da98d63f63070076de ） 分支的话，封面还受这个字段控制：

https://github.com/volantis-x/hexo-theme-volantis/blob/df017f95a7b854b2a91e86da98d63f63070076de/_config.yml#L73-L79

同时，对于文章页，还可以被 front-matter 中 `cover` 字段复写。

**Comment by lovelyJason** [comment]
> hexo-theme-volantis/_config.yml

你好, 我本地已经将volantis仓库main分支最新节点df017f9合并到了我的fork仓库上了,只是还没推送到远程仓库(现在已经推送了,对应着远程fork仓库的分支是dev-theme);我按照你给的这个设置了cover, 封面还是没能出现到

------

甚至还很奇怪, 我把官方博客的config配置文件全部挪到我项目里来, 也没有这个封面, 我对代码的改动应该不足以影响到这个封面的逻辑, 我看到现有的代码里就是layout/_partial/scripts/_ctrl/coverCtr.ejs这个地方把cover样式设置为了隐藏

**Comment by lovelyJason** [comment]
嗯我知道了，被项目下_config.yml中的theme_confg项cover给覆盖了，那里设置了 
display:
      home: false
