### ISSUE TITLE
怎么使用腾讯的前端性能监控

### ISSUE THREAD

**Issue by imjason** [xaoxuu/hexo-theme-volantis#700]
## 需求描述

这个功能在[inkss的提交](https://github.com/volantis-x/hexo-theme-volantis/commit/a39dd0791528a48c12c157070cf95f9fb2814b98)中添加，但是我在阅读文档后未发现vlts的相关配置，希望可以跟进一下文档

**Comment by inkss** [comment]
> [腾讯前端性能监控](https://volantis.js.org/v5/advanced-settings/#%E8%85%BE%E8%AE%AF%E5%89%8D%E7%AB%AF%E6%80%A7%E8%83%BD%E7%9B%91%E6%8E%A7)

![Snipper - Snipaste_22-01-01_20-34-55](https://user-images.githubusercontent.com/31947043/147850670-6a7966a3-eb93-4ccc-8b62-9e2eea7380d7.png)

**Comment by penndu** [comment]
> > [腾讯前端性能监控](https://volantis.js.org/v5/advanced-settings/#%E8%85%BE%E8%AE%AF%E5%89%8D%E7%AB%AF%E6%80%A7%E8%83%BD%E7%9B%91%E6%8E%A7)
> 
> ![Snipper - Snipaste_22-01-01_20-34-55](https://user-images.githubusercontent.com/31947043/147850670-6a7966a3-eb93-4ccc-8b62-9e2eea7380d7.png)

需要装插件吗？还是直接就可以用？

**Comment by inkss** [comment]
直接用就行，当然腾讯云那边需要你自己设置一下。

**Comment by imjason** [comment]
谢谢，已经配置完成了
