### ISSUE TITLE
MathJax 渲染问题

### ISSUE THREAD

**Issue by Firestar-Reimu** [xaoxuu/hexo-theme-volantis#702]
1. 很高兴volantis主题原生支持 MathJax 渲染
2. 第一个问题是：公式换行（比如 `align` 环境）换行符是 `\\\\` 而不是 `\\`
3. 第二个问题是：不支持公式内部的 `aligned` 环境，例如以下代码
```
$$
f(x)=
\left{
\begin{aligned}
& x, x<0\\
& 1, x>0
\end{aligned}
\right.
$$
```
其余语法都和正常的 LaTeX 一样

**Comment by MHuiG** [comment]
问题1见 https://shiraha.cn/2021/use-pandoc-to-render-multiline-formulas-correctly/
问题2:

```
$$
f(x) = \begin{cases} x & x<0 \\ 1 & x>0 \end{cases} .
$$
```

![image](https://user-images.githubusercontent.com/38281581/153167147-ad44fc0a-84e9-4302-829e-2fc2e47c00bf.png)


<blockquote><img src="https://cdn.jsdelivr.net/gh/ymd45921/util_assets@master/favicon/ymd45921/madoka-1/favicon.ico" width="48" align="right"><div><strong><a href="https://shiraha.cn/2021/use-pandoc-to-render-multiline-formulas-correctly/">使用 pandoc 正确渲染多行 MathJax 公式 - 七海の参考書</a></strong></div><div>得益于 mathjax，在静态博客里可以简单的插入数学公式；但是 Hexo 默认的渲染器 marked 并不能正确的渲染多行公式；本文简单考据了一些常见的替代渲染器</div></blockquote>

**Comment by Firestar-Reimu** [comment]
你好，这里还有一个问题就是hexo-renderer-marked如何渲染 `\,` 空格？
