### ISSUE TITLE
tabs 标签插件问题

### ISSUE THREAD

**Issue by ericclose** [xaoxuu/hexo-theme-volantis#703]
结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

tabs 标签无法正常显示，如视频所示：

https://user-images.githubusercontent.com/34526560/149744416-4556c08c-05ad-470c-8e44-cf1d71afdb29.mp4

### 主题版本

您当前使用的版本为：**5.0.0-alpha.5**

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 配置文件 
<details><summary>配置文件</summary>

#### markdown文件

![Snipaste_2022-01-17_18-20-35](https://user-images.githubusercontent.com/34526560/149751752-7646f9f3-70ff-4aec-ab58-2fcaca7ec5a7.png)

试了下 4.3.1 之后的 release 版本都有这个问题

**Comment by inkss** [comment]
方便展示下视频中控制台里显示的 2 个错误信息吗？

![sp20220119_123847_297](https://user-images.githubusercontent.com/31947043/150065399-3bf36ad3-6676-4a5d-ae3c-ef9fb38c276b.png)

**Comment by ericclose** [comment]
> 方便展示下视频中控制台里显示的 2 个错误信息吗？
> 
> ![sp20220119_123847_297](https://user-images.githubusercontent.com/31947043/150065399-3bf36ad3-6676-4a5d-ae3c-ef9fb38c276b.png)

错误信息

```log
VM23:1800 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#1-2' is not a valid selector.
    at HTMLDivElement.ele.find (http://localhost:4000/:1800:24)
    at HTMLAnchorElement.<anonymous> (http://localhost:4000/js/app.js?time=1642575787878.js:341:16)
ele.find @ VM23:1800
(anonymous) @ app.js?time=1642575787878.js:341
app.js?time=1642575787878.js:340 Uncaught TypeError: Cannot read properties of undefined (reading 'removeClass')
    at HTMLAnchorElement.<anonymous> (app.js?time=1642575787878.js:340:44)
(anonymous) @ app.js?time=1642575787878.js:340

```

![image](https://user-images.githubusercontent.com/34526560/150081328-57b6b29a-26ba-49c0-ac25-1c203ff779d6.png)

**Comment by inkss** [comment]
> Failed to execute 'querySelector' on 'Element': '#1-2' is not a valid selector.

如你所见，querySelector 的 selectors 是遵循 CSS 选择器规范的，也就是不允许数字开头，主题这边会做一个判断。

于你那边，可以先将 tabs 的 id 更改为字母开头解决这个问题。

**Comment by xaoxuu** [comment]
可以参考stellar的优化方案，主题自动生成id，既简化的使用方法，又可以防止重复或无效的id

**Comment by inkss** [comment]
> 可以参考stellar的优化方案，主题自动生成id，既简化的使用方法，又可以防止重复或无效的id

@xaoxuu 快来改 （坏笑
