### ISSUE TITLE
关于切换静态CDN或加入freecdn兼容

### ISSUE THREAD

**Issue by MCSeekeri** [xaoxuu/hexo-theme-volantis#705]
## 需求描述
在jsdelivr撤销国内节点之后，站点加载速度大幅度下降，虽然可以在_config.yml里修改js地址为国内静态CDN，但是主题本身的一些文件还是会从jsdelivr加载，所以是否可以考虑将地址统一切换到一个国内unpkg镜像。

也有一个比较复杂的方案是加入对[freecdn](https://github.com/EtherDream/freecdn)这个项目的兼容，但我不大确定这个项目和Hexo的相性如何...

## 参考链接
[freecdn加速第三方URL](https://github.com/EtherDream/freecdn/tree/master/examples/cdn-fallback)

**Comment by inkss** [comment]
主题内引用的的外部资源现在可以在配置文件里修改了
