### ISSUE TITLE
hexo 升级到 6.0.0 并使用noteblock标签会导致文章渲染不正常

### ISSUE THREAD

**Issue by zryyyy** [xaoxuu/hexo-theme-volantis#712]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

## 问题描述

官网的文档就有渲染不正常的问题
https://volantis.js.org/v5/tag-plugins/
![https://volantis.js.org/v5/tag-plugins/](https://i.bmp.ovh/imgs/2022/02/acb751c0f057853f.png)
- 文章的大部分渲染问题出现在标题和侧边栏
- 文章一般是半篇渲染正常，半篇不正常

### 主题版本

您当前使用的版本为：________官网文档版本_________

### 复现地址

- [x] 文档官网源码运行存在异常。https://volantis.js.org/v5/tag-plugins/
- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![https://volantis.js.org/v5/tag-plugins/](https://i.bmp.ovh/imgs/2022/02/acb751c0f057853f.png)

</details>

### 浏览器、操作系统

Edge 97.0.1072.76
Windows 11 Insider Preview

**Comment by zryyyy** [comment]
现在基本上确定了是hexo-renderer-marked这个插件的问题，我从4.1.0升级到5.0.0以后就会出现文章渲染错误

**Comment by MHuiG** [comment]
hexo 升级到 6.0.0 会导致这个问题
https://github.com/volantis-x/community/commit/95f1bbe4153375a8185610328ce9d81d6da27cbf

**Comment by zryyyy** [comment]
> hexo 升级到 6.0.0 会导致这个问题 [volantis-x/community@95f1bbe](https://github.com/volantis-x/community/commit/95f1bbe4153375a8185610328ce9d81d6da27cbf)

我感觉部署hexo6.0.0的问题
我拿了之前一个版本的备份测试的，hexo升级6.0.0不会有问题，但是hexo-renderer-marked从4.1.0升级到5.0.0以后就会出现问题

**Comment by MHuiG** [comment]
"hexo": "^5.4.1",
"hexo-renderer-marked": "^5.0.0",
这个配置是正常的
https://volantis.js.org/v5/tag-plugins/

<blockquote><img src="https://npm.elemecdn.com/hexo-theme-volantis@5.0.0-beta.2/source/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/v5/tag-plugins/">标签插件</a></strong></div><div>为了兼容老用户，旧的标签插件在重构之前依然沿用旧的格式，即 command + 空格 作为参数分隔符，而部分新增标签插件是 空格 + 英文竖线 + 空格 ，请注意区分。  我们也在探索哪种分隔符既简单又不容易引起冲突，所以可能存在多种格式，具体以对应文档描述为准。  5.0 版本起临时实验使用英文双冒号 ( :: ) 作为分隔符，之前版本的分隔符写法向下兼容  5.0 版本的分隔符最终计划使用 s</div></blockquote>

**Comment by zryyyy** [comment]
那我感觉可能是两个一起用的时候出现问题

**Comment by MHuiG** [comment]
我也不知道为什么，就很奇怪

**Comment by MHuiG** [comment]
https://github.com/hexojs/hexo/issues/4884

**Comment by zryyyy** [comment]
看起来hexo升级到6.1.0还是没有解决这个bug

**Comment by MHuiG** [comment]
破案了，Hexo 6.x 不能用 noteblock 注册为标签名称，试过noteb,notebl,noteblo,notebloc都不行，但是blocknote却可以，就很邪门

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/6a134b499e53e2a6d73878c01b103bd7f984cb30/scripts/tags/note.js#L50-L51

**Comment by xaoxuu** [comment]
我看了下好像我们只有note标签有对应的noteblock标签，可能是这种命名格式冲突了，不知道别的标签后面加个block注册个新标签是不是也会出问题

**Comment by xingpingcn** [comment]
如果有多个noteblock或者blocknote也会出错。unknown block tag: endblocknote。仅有一个就不会报错
