### ISSUE TITLE
【建议】：修改行内代码的字体

### ISSUE THREAD

**Issue by Firestar-Reimu** [xaoxuu/hexo-theme-volantis#729]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

修改行内代码的字体，例如 `this font should be a monospaced-font`

现在只能改正文/行间代码块的字体，例如 https://blog.firestar-reimu.top/Manjaro-KDE-Installation/ 这篇文章只有行间代码字体都改成了JB Mono

### 参考链接

https://inkss.cn/blog/bbb93a9b/ 这篇文章成功把行内和行间代码字体都改成了JB Mono

https://developer.mozilla.org/zh-CN/docs/Web/CSS/font-family

**Comment by inkss** [comment]
你把这行改成：`font-family: $fontfamily-code` 吧。

https://github.com/volantis-x/hexo-theme-volantis/blob/99b7252c68177843f37e3179e9f916a83d1bbdf7/source/css/_style/_layout/article.styl#L142

**Comment by Firestar-Reimu** [comment]
> 你把这行改成：font-family: $fontfamily-code 吧。

可解决！非常感谢，希望可以有一个comment，代码应该是同一类字体比较合理，否则我为什么需要行内代码功能呢？
