### ISSUE TITLE
【问题】：Latex公式不能渲染

### ISSUE THREAD

**Issue by EJayyyyyyyyy** [xaoxuu/hexo-theme-volantis#733]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.0

### 复现地址

http://49.233.16.187:4000/2022/03/27/%E8%BD%AF%E8%80%83%E7%BD%91%E5%B7%A5%E7%AC%94%E8%AE%B0%E2%80%94%E2%80%94%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89/#%E4%B8%AD%E5%A4%AE%E5%A4%84%E7%90%86%E5%99%A8%EF%BC%88CPU%EF%BC%89%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84

### 问题描述

Latex公式不能渲染

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by EJayyyyyyyyy** [comment]
刚才在群里问了,改front-matter也没用，不知道问题出在哪里了

**Comment by MHuiG** [comment]
https://volantis.js.org/v5/page-settings/?keyword=math

<blockquote><img src="https://volantis.js.org/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/v5/page-settings/">页面配置</a></strong></div><div>页面布局模板布局模板   取值 含义    page 独立页面   post 文章页面   docs 文档页面   category 分类页面   tag 标签页面   friends 友链页面   list 列表页面     page & post & docs这三种页面相同，但是有以下细微区别：  post 文章有 title 时，向下滚动网页，导航栏会向上移出屏幕显出文章标题</div></blockquote>
