### ISSUE TITLE
mathjax无法换行

### ISSUE THREAD

**Issue by zryyyy** [xaoxuu/hexo-theme-volantis#736]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.0.0-alpha.11

### 复现地址

https://s1.ax1x.com/2022/04/07/qxNbb6.png

### 问题描述

```latex
\int k\mathrm{d}x = kx + C \\
\int x^{\mu}\mathrm{d}x = \frac{x^{\mu + 1}}{\mu + 1} + C
```
`\\`无法实现换行功能
在找了网上的方法把`\\`替换为`\\\\`后依然无法换行
![qxNbb6.png](https://s1.ax1x.com/2022/04/07/qxNbb6.png)
![qxNHDx.png](https://s1.ax1x.com/2022/04/07/qxNHDx.png)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
$ node -v
v16.14.0

$ npm -v
8.3.1
```
</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
$ npm ls --depth 0
hexo-site@0.0.0 D:\Git\hexo
├── bindings@1.5.0 extraneous
├── file-uri-to-path@1.0.0 extraneous
├── hexo-deployer-git@3.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-search@2.4.3
├── hexo-generator-sitemap@3.0.1
├── hexo-generator-tag@1.0.0
├── hexo-helper-qrcode@1.0.2
├── hexo-related-popular-posts@5.0.1
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@3.0.0
├── hexo-wordcount@6.0.1
├── hexo@6.1.0
└── nan@2.15.0 extraneous
```

</p></details>

**Comment by inkss** [comment]
```latex
\begin{array}{l}
\int k\mathrm{d}x = kx + C \\\\
\int x^{\mu}\mathrm{d}x = \frac{x^{\mu + 1}}{\mu + 1} + C  
\end{array} 
```

**Comment by zryyyy** [comment]
> ```
> \begin{array}{l}
> \int k\mathrm{d}x = kx + C \\\\
> \int x^{\mu}\mathrm{d}x = \frac{x^{\mu + 1}}{\mu + 1} + C  
> \end{array} 
> ```

谢谢大佬，换成array环境以后行了😘

**Comment by zryyyy** [comment]
感觉好像还是有点问题
```
$$
\begin{align}
     & \int {f( ax + b){\rm{d}}x = }\frac{1}{a}\int {f(ax+b){\mathrm{d}}(ax + b)\;(a \neq 0)}                                                              \\[7pt]
     & \int {f(a{x^{m + 1}} + b){x^m}{\rm{d}}x} = \frac{1}{{a(m + 1)}}\int {f(a{x^{m + 1}} + b){\rm{d}}(a{x^{m + 1}} + b)}                                 \\[7pt]
     & \int {f\left( \frac{1}{x}\right) \frac{{{\rm{d}}x}}{{{x^2}}}\;}  =  - \int {f\left( \frac{1}{x}\right) {\rm{d}}\left( \frac{{\rm{1}}}{x}\right) \;} \\[7pt]
     & \int {f(\ln x)\frac{1}{x}} {\rm{d}}x = \int {f(\ln x){\rm{d(}}\ln x)}                                                                               \\[7pt]
     & \int {f({\mathrm{e}^x})} {\mathrm{e}^x}{\rm{d}}x = \int {f({\mathrm{e}^x}} ){\rm{d(}}{\mathrm{e}^x})                                                \\[7pt]
     & \int {f(\sqrt x } )\frac{{{\rm{d}}x}}{{\sqrt x }} = 2\int {f(\sqrt x } ){\rm{d}}(\sqrt x )                                                          \\[7pt]
     & \int {f(\sin x)\cos x{\rm{d}}x = } \int {f(\sin x){\rm{d}}\sin x}                                                                                   \\[7pt]
     & \int {f(\cos x)\sin x{\rm{d}}x = }  - \int {f(\cos x){\rm{d}}\cos x}                                                                                \\[7pt]
     & \int {f(\tan x){{\sec }^2}} x{\rm{d}}x = \int {f(\tan x){\rm{d}}\tan x}                                                                             \\[7pt]
     & \int {f(\cot x){{\csc }^2}} x{\rm{d}}x =  - \int {f(\cot x){\rm{d}}\cot x}                                                                          \\[7pt]
     & \int {f(\arcsin x)\frac{1}{{\sqrt {1 - {x^2}} }}} {\rm{d}}x = \int {f(\arcsin x){\rm{d}}\arcsin x}                                                  \\[7pt]
     & \int {f(\arctan x)\frac{1}{{1 + {x^2}}}} {\rm{d}}x = \int {f(\arctan x){\rm{d}}\arctan x}                                                           \\[7pt]
     & \int {\frac{{f'(x)}}{{f(x)}}} {\rm{d}}x = \int {\frac{{{\rm{d}}f(x)}}{{f(x)}}}  = \ln \left| f(x)\right| + C
\end{align}
$$
```
这段正常渲染应该是这样的
![](https://s1.ax1x.com/2022/04/07/LSYfdf.png)
下面是报错
```
INFO  Start processing
FATAL {
  err: Error [Nunjucks Error]: _posts/常见的数学公式.md [Line 33, Column 519] parseAggregate: expected colon after dict key
      =====               Context Dump               =====
      === (line number probably different from source) ===
    28 | <h3 id="基本积分方法"><a href="#基本积分方法" class="headerlink" title="基本积分方法"></a>基本积分方法</h3><h4 id="第一类换元法"><a href="#第一类换元法" class="headerlink" title="第一类换元法"></a>第一类换元法</h4><h5 id="三角函数之积的积分"><a href="#三角函数之积的积分" class="headerlink" title="三角函数之积的积分"></a>三角函数之积的积分</h5><ol>
    29 | <li>一般地,对于$ \sin^{2k+1}x\cos^n x $或$ \sin^n x \cos^{2k+1}x $ (其中$ k\in\mathbb{N} $) 型函数的积分,总可依次作变换$ u&#x3D;\cos x $或$ u&#x3D;\sin x $,从而求得结果</li>
    30 | <li>一般地,对于$ \sin^{2k}x\cos^{2l}x $或 (其中$ k,l\in \mathbb{N} $) 型函数的积分,总是利用降幂公式$ \sin^2&#x3D;\dfrac{1}{2}(1-\cos 2x),\cos^2&#x3D;\dfrac{1}{2}(1+\cos 2x) $化成$ \cos 2x $的多项式,从而求得结果</li>
    31 | <li>一般地,对于$ \tan^{n}x\sec^{2k} x $或$ \tan^{2k-1} x \sec^{n}x $ (其中$ n,k\in\mathbb{N}_{+} $) 型函数的积分,总可依次作变换$ u&#x3D;\tan x $或$ u&#x3D;\sec x $,从而求得结果</li>  
    32 | </ol>
    33 | <h5 id="常见的凑微分类型"><a href="#常见的凑微分类型" class="headerlink" title="常见的 凑微分类型"></a>常见的凑微分类型</h5><p>$$<br>\begin{align}<br>     &amp; \int {f( ax + b){\rm{d}}x &#x3D; }\frac{1}{a}\int {f(ax+b){\mathrm{d}}(ax + b)\,(a \neq 0)}                           
                                   \\[7pt]<br>     &amp; \int {f(a{x^{m + 1}} + b){x^m}{\rm{d}}x} &#x3D; \frac{1}{{a(m + 1)}}\int {f(a{x^{m + 1}} + b){\rm{d}}(a{x^{m + 1}} + b)}               
                  \\[7pt]<br>     &amp; \int {f\left( \frac{1}{x}\right) \frac{{{\rm{d}}x}}{{{x^2}}}}  &#x3D;  - \int {f\left( \frac{1}{x}\right) {\rm{d}}\left( \frac{{\rm{1}}}{x}\right) } \\[7pt]<br>     &amp; \int {f(\ln x)\frac{1}{x}} {\rm{d}}x &#x3D; \int {f(\ln x){\rm{d(}}\ln x)}                                                                               \\[7pt]<br>     &amp; \int {f({\mathrm{e}^x})} {\mathrm{e}^x}{\rm{d}}x &#x3D; \int {f({\mathrm{e}^x}} ){\rm{d(}}{\mathrm{e}^x})                                                \\[7pt]<br>     &amp; \int {f(\sqrt x } )\frac{{{\rm{d}}x}}{{\sqrt x }} &#x3D; 2\int {f(\sqrt x } ){\rm{d}}(\sqrt x )                
                                          \\[7pt]<br>     &amp; \int {f(\sin x)\cos x{\rm{d}}x &#x3D; } \int {f(\sin x){\rm{d}}\sin x}                                                          
                         \\[7pt]<br>     &amp; \int {f(\cos x)\sin x{\rm{d}}x &#x3D; }  - \int {f(\cos x){\rm{d}}\cos x}                                                                        
        \\[7pt]<br>     &amp; \int {f(\tan x){{\sec }^2}} x{\rm{d}}x &#x3D; \int {f(\tan x){\rm{d}}\tan x}                                                                             \\[7pt]<br>     &amp; \int {f(\cot x){{\csc }^2}} x{\rm{d}}x &#x3D;  - \int {f(\cot x){\rm{d}}\cot x}                                                                          \\[7pt]<br>     &amp; \int {f(\arcsin x)\frac{1}{{\sqrt {1 - {x^2}} }}} {\rm{d}}x &#x3D; \int {f(\arcsin x){\rm{d}}\arcsin x}                                                  \\[7pt]<br>     &amp; \int {f(\arctan x)\frac{1}{{1 + {x^2}}}} {\rm{d}}x &#x3D; \int {f(\arctan x){\rm{d}}\arctan x}                       
                                    \\[7pt]<br>     &amp; \int {\frac{{f'(x)}}{{f(x)}}} {\rm{d}}x &#x3D; \int {\frac{{{\rm{d}}f(x)}}{{f(x)}}}  &#x3D; \ln \left| f(x)\right| + C<br>\end{align}<br>$$</p>
    34 |
      =====             Context Dump Ends            =====
      at formatNunjucksError (D:\Git\hexo\node_modules\hexo\lib\extend\tag.js:171:13)
      at D:\Git\hexo\node_modules\hexo\lib\extend\tag.js:246:36
      at tryCatcher (D:\Git\hexo\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:725:18)
      at _drainQueueStep (D:\Git\hexo\node_modules\bluebird\js\release\async.js:93:12)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\Git\hexo\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:466:21) {
    line: 33,
    location: '\x1B[35m_posts/常见的数学公式.md\x1B[39m [Line 33, Column 519]',
    type: 'parseAggregate: expected colon after dict key'
```

**Comment by zryyyy** [comment]
> 感觉好像还是有点问题
> 
> ```
> $$
> \begin{align}
>      & \int {f( ax + b){\rm{d}}x = }\frac{1}{a}\int {f(ax+b){\mathrm{d}}(ax + b)\;(a \neq 0)}                                                              \\[7pt]
>      & \int {f(a{x^{m + 1}} + b){x^m}{\rm{d}}x} = \frac{1}{{a(m + 1)}}\int {f(a{x^{m + 1}} + b){\rm{d}}(a{x^{m + 1}} + b)}                                 \\[7pt]
>      & \int {f\left( \frac{1}{x}\right) \frac{{{\rm{d}}x}}{{{x^2}}}\;}  =  - \int {f\left( \frac{1}{x}\right) {\rm{d}}\left( \frac{{\rm{1}}}{x}\right) \;} \\[7pt]
>      & \int {f(\ln x)\frac{1}{x}} {\rm{d}}x = \int {f(\ln x){\rm{d(}}\ln x)}                                                                               \\[7pt]
>      & \int {f({\mathrm{e}^x})} {\mathrm{e}^x}{\rm{d}}x = \int {f({\mathrm{e}^x}} ){\rm{d(}}{\mathrm{e}^x})                                                \\[7pt]
>      & \int {f(\sqrt x } )\frac{{{\rm{d}}x}}{{\sqrt x }} = 2\int {f(\sqrt x } ){\rm{d}}(\sqrt x )                                                          \\[7pt]
>      & \int {f(\sin x)\cos x{\rm{d}}x = } \int {f(\sin x){\rm{d}}\sin x}                                                                                   \\[7pt]
>      & \int {f(\cos x)\sin x{\rm{d}}x = }  - \int {f(\cos x){\rm{d}}\cos x}                                                                                \\[7pt]
>      & \int {f(\tan x){{\sec }^2}} x{\rm{d}}x = \int {f(\tan x){\rm{d}}\tan x}                                                                             \\[7pt]
>      & \int {f(\cot x){{\csc }^2}} x{\rm{d}}x =  - \int {f(\cot x){\rm{d}}\cot x}                                                                          \\[7pt]
>      & \int {f(\arcsin x)\frac{1}{{\sqrt {1 - {x^2}} }}} {\rm{d}}x = \int {f(\arcsin x){\rm{d}}\arcsin x}                                                  \\[7pt]
>      & \int {f(\arctan x)\frac{1}{{1 + {x^2}}}} {\rm{d}}x = \int {f(\arctan x){\rm{d}}\arctan x}                                                           \\[7pt]
>      & \int {\frac{{f'(x)}}{{f(x)}}} {\rm{d}}x = \int {\frac{{{\rm{d}}f(x)}}{{f(x)}}}  = \ln \left| f(x)\right| + C
> \end{align}
> $$
> ```
> 
> 这段正常渲染应该是这样的 ![](https://camo.githubusercontent.com/ac59b7e9e8294cc4881784cf57a461d12561ff846f66b1eb0ffc60612bd72186/68747470733a2f2f73312e617831782e636f6d2f323032322f30342f30372f4c53596664662e706e67) 下面是报错
> 
> ```
> INFO  Start processing
> FATAL {
>   err: Error [Nunjucks Error]: _posts/常见的数学公式.md [Line 33, Column 519] parseAggregate: expected colon after dict key
>       =====               Context Dump               =====
>       === (line number probably different from source) ===
>     28 | <h3 id="基本积分方法"><a href="#基本积分方法" class="headerlink" title="基本积分方法"></a>基本积分方法</h3><h4 id="第一类换元法"><a href="#第一类换元法" class="headerlink" title="第一类换元法"></a>第一类换元法</h4><h5 id="三角函数之积的积分"><a href="#三角函数之积的积分" class="headerlink" title="三角函数之积的积分"></a>三角函数之积的积分</h5><ol>
>     29 | <li>一般地,对于$ \sin^{2k+1}x\cos^n x $或$ \sin^n x \cos^{2k+1}x $ (其中$ k\in\mathbb{N} $) 型函数的积分,总可依次作变换$ u&#x3D;\cos x $或$ u&#x3D;\sin x $,从而求得结果</li>
>     30 | <li>一般地,对于$ \sin^{2k}x\cos^{2l}x $或 (其中$ k,l\in \mathbb{N} $) 型函数的积分,总是利用降幂公式$ \sin^2&#x3D;\dfrac{1}{2}(1-\cos 2x),\cos^2&#x3D;\dfrac{1}{2}(1+\cos 2x) $化成$ \cos 2x $的多项式,从而求得结果</li>
>     31 | <li>一般地,对于$ \tan^{n}x\sec^{2k} x $或$ \tan^{2k-1} x \sec^{n}x $ (其中$ n,k\in\mathbb{N}_{+} $) 型函数的积分,总可依次作变换$ u&#x3D;\tan x $或$ u&#x3D;\sec x $,从而求得结果</li>  
>     32 | </ol>
>     33 | <h5 id="常见的凑微分类型"><a href="#常见的凑微分类型" class="headerlink" title="常见的 凑微分类型"></a>常见的凑微分类型</h5><p>$$<br>\begin{align}<br>     &amp; \int {f( ax + b){\rm{d}}x &#x3D; }\frac{1}{a}\int {f(ax+b){\mathrm{d}}(ax + b)\,(a \neq 0)}                           
>                                    \\[7pt]<br>     &amp; \int {f(a{x^{m + 1}} + b){x^m}{\rm{d}}x} &#x3D; \frac{1}{{a(m + 1)}}\int {f(a{x^{m + 1}} + b){\rm{d}}(a{x^{m + 1}} + b)}               
>                   \\[7pt]<br>     &amp; \int {f\left( \frac{1}{x}\right) \frac{{{\rm{d}}x}}{{{x^2}}}}  &#x3D;  - \int {f\left( \frac{1}{x}\right) {\rm{d}}\left( \frac{{\rm{1}}}{x}\right) } \\[7pt]<br>     &amp; \int {f(\ln x)\frac{1}{x}} {\rm{d}}x &#x3D; \int {f(\ln x){\rm{d(}}\ln x)}                                                                               \\[7pt]<br>     &amp; \int {f({\mathrm{e}^x})} {\mathrm{e}^x}{\rm{d}}x &#x3D; \int {f({\mathrm{e}^x}} ){\rm{d(}}{\mathrm{e}^x})                                                \\[7pt]<br>     &amp; \int {f(\sqrt x } )\frac{{{\rm{d}}x}}{{\sqrt x }} &#x3D; 2\int {f(\sqrt x } ){\rm{d}}(\sqrt x )                
>                                           \\[7pt]<br>     &amp; \int {f(\sin x)\cos x{\rm{d}}x &#x3D; } \int {f(\sin x){\rm{d}}\sin x}                                                          
>                          \\[7pt]<br>     &amp; \int {f(\cos x)\sin x{\rm{d}}x &#x3D; }  - \int {f(\cos x){\rm{d}}\cos x}                                                                        
>         \\[7pt]<br>     &amp; \int {f(\tan x){{\sec }^2}} x{\rm{d}}x &#x3D; \int {f(\tan x){\rm{d}}\tan x}                                                                             \\[7pt]<br>     &amp; \int {f(\cot x){{\csc }^2}} x{\rm{d}}x &#x3D;  - \int {f(\cot x){\rm{d}}\cot x}                                                                          \\[7pt]<br>     &amp; \int {f(\arcsin x)\frac{1}{{\sqrt {1 - {x^2}} }}} {\rm{d}}x &#x3D; \int {f(\arcsin x){\rm{d}}\arcsin x}                                                  \\[7pt]<br>     &amp; \int {f(\arctan x)\frac{1}{{1 + {x^2}}}} {\rm{d}}x &#x3D; \int {f(\arctan x){\rm{d}}\arctan x}                       
>                                     \\[7pt]<br>     &amp; \int {\frac{{f'(x)}}{{f(x)}}} {\rm{d}}x &#x3D; \int {\frac{{{\rm{d}}f(x)}}{{f(x)}}}  &#x3D; \ln \left| f(x)\right| + C<br>\end{align}<br>$$</p>
>     34 |
>       =====             Context Dump Ends            =====
>       at formatNunjucksError (D:\Git\hexo\node_modules\hexo\lib\extend\tag.js:171:13)
>       at D:\Git\hexo\node_modules\hexo\lib\extend\tag.js:246:36
>       at tryCatcher (D:\Git\hexo\node_modules\bluebird\js\release\util.js:16:23)
>       at Promise._settlePromiseFromHandler (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:547:31)
>       at Promise._settlePromise (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:604:18)
>       at Promise._settlePromise0 (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:649:10)
>       at Promise._settlePromises (D:\Git\hexo\node_modules\bluebird\js\release\promise.js:725:18)
>       at _drainQueueStep (D:\Git\hexo\node_modules\bluebird\js\release\async.js:93:12)
>       at Immediate.Async.drainQueues [as _onImmediate] (D:\Git\hexo\node_modules\bluebird\js\release\async.js:15:14)
>       at processImmediate (node:internal/timers:466:21) {
>     line: 33,
>     location: '\x1B[35m_posts/常见的数学公式.md\x1B[39m [Line 33, Column 519]',
>     type: 'parseAggregate: expected colon after dict key'
> ```

\\\\和\\;我也试过但是也没用

**Comment by MHuiG** [comment]
`{{`和 `}}` 是 hexo 模板语法 需要注释掉 `\{\{` `\}\}`

**Comment by zryyyy** [comment]
> `{{`和 `}}` 是 hexo 模板语法 需要注释掉 `\{\{` `\}\}`

噢噢谢谢大佬
