### ISSUE TITLE
【其它】：主题开发行动，请求加入 volantis 系列

### ISSUE THREAD

**Issue by Tikas** [xaoxuu/hexo-theme-volantis#748]
### 议题内容

之前一直有在偷偷学习 css，为了学以致用，加上又喜欢 volantis，理所当然想给自己的首个主题开发加入 volantis-X 里。

目的：

* 让 volantis-X 成为一个开源主题集合社区
* 同时也想让 volantis-X 里所有的主题能配置互通，让 volantis 成为 hexo 主题里最为灵活多用的主题系列
* 当然也是一个甩手给 @xaoxuu 接手开发的很好机会

当然，现在我还在学习 css，js 还没开始学习，开发的进度会比较缓慢，毕竟是零开发经验。

**Comment by Tikas** [comment]
这只是一个请求，如果认为这并不是一个很好的主意，那么我会另起一个名字单独开发了。

虽然我很想起一个 volantis-S ，S 是 岁月的拼音缩写，流金岁月，让写作文章更具有时光纪念意义，当然，我的构思不仅仅只有这一点，更多等主题有个演示之后再来给 @xaoxuu 等开发者们一起审核，没问题之后才公布。

**Comment by xaoxuu** [comment]
太棒了，强烈欢迎👏

**Comment by Tikas** [comment]
👌
