### ISSUE TITLE
【建议】：添加51la统计

### ISSUE THREAD

**Issue by imjason** [xaoxuu/hexo-theme-volantis#756]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

如题，百度割韭菜，cnzz非备案不能使用，建议加一个备用

**Comment by imjason** [comment]
51.la

**Comment by inkss** [comment]
`config.v6_51_la` e894d34e4615bf4a778acaaabccdf3e35822e2ef
