### ISSUE TITLE
【问题】：在手机端UC，QQ浏览器以及微信内置浏览器点击代码块Copy按钮后报错

### ISSUE THREAD

**Issue by AlexLiu657** [xaoxuu/hexo-theme-volantis#758]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [ ] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

Volantis 5.0.0-rc.101

### 复现地址

https://volantis.js.org/v5/getting-started/  或者 https://it65720.top/202205171260b55f.html

### 问题：
把我的博客链接通过微信发给朋友后，直接点击微信中的链接进去后，使用代码块的Copy按钮报错，内容复制失败，也没有加入剪切板，然后尝试了一下官网和其他朋友们的博客，同样有一样的问题，然后复制文章内容是正常的，目前测试了微信内置浏览器，手机QQ浏览器，手机UC浏览器，测试不通过，手机内置浏览器，测试通过，可以正常复制，测试机型小米10，小米6
![微信图片_20220517124327.jpg](https://bu.dusays.com/2022/05/17/628329266176a.jpg)

![微信图片_20220517124711.jpg](https://bu.dusays.com/2022/05/17/628329287370d.jpg)

### 问题重现方式：

使用手机微信内置浏览器，手机QQ浏览器，手机UC浏览器进入一个有代码块的页面如https://volantis.js.org/v5/getting-started/，点击代码块右上角的Copy按钮进行全部代码的复制即可重现

### 问题自查（未解决）：

发现问题后自己尝试查看找到 themes\volantis\source\js\app.js 中有一段是复制粘贴的代码写上了一些alert()（其他代码未修改）,后来报错如下，于是去查看手机对应的权限，给足权限后依旧不行，遂请求帮助

![微信图片_20220517130630.png](https://bu.dusays.com/2022/05/17/62832d8f51d76.png)

![微信图片_20220517125850.jpg](https://bu.dusays.com/2022/05/17/62832e5aed4cc.jpg)

![微信图片_20220517124538.jpg](https://bu.dusays.com/2022/05/17/62832926cc2d2.jpg)
### 部署以及主题安装配置方式
直接下载了tag5.0.0-rc.101中的zip包解压进行安装，配置过程均参考官网相关进行进行配置修改，部署在githubpages

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by penndu** [comment]
刚去看了一下，貌似PC端也有问题！

**Comment by AlexLiu657** [comment]
> 刚去看了一下，貌似PC端也有问题！

我这边测试了一下PC端是可以的，用的是Chromium 86.0.4240.198内核

**Comment by MHuiG** [comment]
@AlexLiu657 你看看 https://clipboardjs.com/ 里面的[Copy按钮 在你的浏览器里正常工作吗

<blockquote><img src="https://zenorocha.github.io/clipboard.js/assets/images/facebook.png" width="48" align="right"><div><strong><a href="https://zenorocha.github.io/clipboard.js/">clipboard.js</a></strong></div><div>A modern approach to copy text to clipboard. No Flash. No frameworks. Just 3kb gzipped</div></blockquote>

**Comment by AlexLiu657** [comment]
@MHuiG 这个组件可以的，我测试了小米10和小米6的微信的内置浏览器，手机QQ浏览器还有UC浏览器，杜老师上午说的应该是PC端的微信内置浏览器，我试了一下也是OK的

**Comment by MHuiG** [comment]
@inkss 我感觉是这里 return 出去了 然后没有执行后面的 catch

https://github.com/volantis-x/hexo-theme-volantis/blob/bfff2523d672ba657e6e9f20e2bb12291bc71ba4/source/js/app.js#L446-L448

https://github.com/volantis-x/hexo-theme-volantis/blob/bfff2523d672ba657e6e9f20e2bb12291bc71ba4/source/js/app.js#L449-L468

**Comment by MHuiG** [comment]
@AlexLiu657 测试一下是否修复了

https://volantis-x.js.org/test/markdown/

<blockquote><img src="https://npm.elemecdn.com/volantis-static@0.0.1649552113628/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://npm.elemecdn.com/volantis-static@0.0.1649552113628/media/org.volantis/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/test/markdown/">Markdown Style test</a></strong></div><div>This post is originated from here and is used for testing markdown style. This post contains nearly every markdown usage. Make sure all the markdown elements below show up correctly.</div></blockquote>

**Comment by AlexLiu657** [comment]
@MHuiG 目前在昨天同样的环境下测试可以进行复制，但是复制出来的代码会聚在一起，失去了换行，然后我用手机自带的浏览器测试了一下老方法的复制测试一下之前的代码块（手机自带浏览器可以进行复制），是带换行的，同时也测试了一下[clipboard.js](https://zenorocha.github.io/clipboard.js/)才发现他们自带的DEMO也是没有换行的QAQ
![image](https://user-images.githubusercontent.com/65706242/168959339-8dbbd07e-09f2-493b-b188-7adab9551b96.png)
[![Snipaste_2022-05-18_12-38-38.png](https://bu.dusays.com/2022/05/18/62847a7dbe2db.png)](https://bu.dusays.com/2022/05/18/62847a7dbe2db.png)

**Comment by AlexLiu657** [comment]
@MHuiG 补充一下，https://volantis-x.js.org/test/markdown/的PC端是OK的😂😂，复制出来是带换行的

**Comment by MHuiG** [comment]
是这么个逻辑，主题里面有两套复制方案，

一套是有换行的但是兼容性差，有的浏览器不支持

不支持的话会使用第二套方案，这套方案抄的[clipboard.js](https://zenorocha.github.io/clipboard.js/) 兼容性较好

**Comment by inkss** [comment]
把这里换成 textarea 试试。

https://github.com/volantis-x/hexo-theme-volantis/blob/9fdbff382cc6f1640de82bc0728fabd86d71511e/source/js/app.js#L446

**Comment by MHuiG** [comment]
我记得clipboard.js就是textarea

**Comment by MHuiG** [comment]
https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.js#L76

<blockquote><img src="https://opengraph.githubassets.com/b197a0856d0b9928d0d80fd0eb441fe6aa9f75fce6a2e7d9c517bd91555b825c/zenorocha/clipboard.js" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/zenorocha/clipboard.js">clipboard.js/clipboard.js at master · zenorocha/clipboard.js</a></strong></div><div>:scissors: Modern copy to clipboard. No Flash. Just 3kb gzipped :clipboard: - clipboard.js/clipboard.js at master · zenorocha/clipboard.js</div></blockquote>

**Comment by inkss** [comment]
小米浏览器能禁止网页写入剪切板，不知道怎么实现的，主题没捕获到错误，依旧报了复制成功

**Comment by AlexLiu657** [comment]
多谢各位大佬们的帮助，就是想知道后面这个代码格式的问题还会解嘛😂

**Comment by AlexLiu657** [comment]
@MHuiG @inkss 上面inkss大佬说的对，Volantis 5.0.0-rc.111中的app.js这一块修改成这样就可以解决代码格式的问题了，非常感谢你们的帮忙
![微信图片_20220518210310.png](https://bu.dusays.com/2022/05/18/6284eed57f3f0.png)

**Comment by MHuiG** [comment]
innerHTML是吧 快去给 clipboard.js PR修一下

**Comment by AlexLiu657** [comment]
@MHuiG 这个速度这个时间点了😂，点个大大的赞
