### ISSUE TITLE
【错误】：cdn.jsdelivr 相关资源国内不可用

### ISSUE THREAD

**Issue by dxc0522** [xaoxuu/hexo-theme-volantis#759]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [ ] 已经将主题升级到最新版本。
- [ ] 主题官网也存在这个问题。

### 复现步骤

cdn.jsdelivr 国内域名不可用,所有相关资源都无法打开,cdn全部失效,博客已经无法正常使用.
是否有修复版?或者修复方案?

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/d25a39163765eeca5306a1daa6e8d6f16e4ba643/_config.yml#L61-L68

**Comment by MHuiG** [comment]
https://fastly.jsdelivr.net/npm/ 还能用

**Comment by MHuiG** [comment]
https://fastly.jsdelivr.net/ 还能用

<blockquote><img src="https://www.jsdelivr.com/img/logo@2x.png" width="48" align="right"><div>jsDelivr</div><div><strong><a href="https://www.jsdelivr.com/">jsDelivr - A free, fast, and reliable CDN for Open Source</a></strong></div><div>Supports npm, GitHub, WordPress, Deno, and more. Largest network and best performance among all CDNs. Serving more than 80 billion requests per month. Built for production use.</div></blockquote>

**Comment by dxc0522** [comment]
> https://fastly.jsdelivr.net/可以使用
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/9b31a7d070cd0ddc125e825f3632762b89b75398413411ff1bb2e2b9827af4e2/68747470733a2f2f7777772e6a7364656c6976722e636f6d2f696d672f6c6f676f4032782e706e67">jsDelivr**[jsDelivr - 一个免费、快速、可靠的开源 CDN](https://www.jsdelivr.com/)**支持 npm、GitHub、WordPress、Deno 等。所有 CDN 中最大的网络和最佳性能。每月处理超过 800 亿个请求。专为生产使用而设计。

**Comment by penndu** [comment]
gcore.jsdelivr.net试一下

**Comment by dxc0522** [comment]
好的,万分感谢
