### ISSUE TITLE
Waline2.5.0导致手机端布局过宽

### ISSUE THREAD

**Issue by zryyyy** [xaoxuu/hexo-theme-volantis#761]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.1.0

### 复现地址

https://test.zryyyy.xyz/2022-04-05-%E9%AB%98%E6%95%B0%E5%B8%B8%E8%A7%81%E7%9A%84%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F/

### 问题描述

Waline2.5.0版本更新了搜索表情包的功能导致了手机浏览器加载完后右边会多出一块
![](https://i.bmp.ovh/imgs/2022/05/19/494dce50edeeb626.png)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by MHuiG** [comment]
要不我们把它回滚吧

https://github.com/volantis-x/hexo-theme-volantis/commit/24b2d9809c9c2239469d4a85a06dd2bac3769c76

https://github.com/volantis-x/hexo-theme-volantis/pull/755

**Comment by zryyyy** [comment]
> 要不我们把它回滚吧
> 
> [24b2d98](https://github.com/volantis-x/hexo-theme-volantis/commit/24b2d9809c9c2239469d4a85a06dd2bac3769c76)
> 
> #755

那这样表情不是被挡住了...😶

**Comment by MHuiG** [comment]
https://github.com/walinejs/waline/pull/1040
