### ISSUE TITLE
【问题】：random wallpaper api 403

### ISSUE THREAD

**Issue by ayang0** [xaoxuu/hexo-theme-volantis#776]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [ ] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [ ] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.4.0

### 复现地址

https://www.ayang.ga/

### 问题描述

![image](https://user-images.githubusercontent.com/52871496/174337574-3a02e3c5-af5d-43ba-af72-ddc52fe666b9.png)

############################### Cover ############################### > start
cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
  # background: https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: 'Volantis'
  subtitle: ''
  search: A Wonderful Theme for Hexo # search bar placeholder
  features:
    - name: 文档
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: /v4/getting-started/
    - name: 帮助
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f516.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
      url: faqs/
    - name: 示例
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f396.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f396.svg
      url: /examples/
    - name: 社区
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f389.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
      url: /contributors/
    - name: 博客
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 源码
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/volantis-x/hexo-theme-volantis/

**Comment by penndu** [comment]
你的api没权限。
![image](https://user-images.githubusercontent.com/46226528/174348951-75b7129a-5f5f-4205-b8f5-c08cbbaf2be2.png)

**Comment by MHuiG** [comment]
https://github.com/MHG-LAB/api/blob/main/api.js#L47

这种api可以自己写个自己用

<blockquote><img src="https://opengraph.githubassets.com/867e8c349a4cfe12e734058ba6603b6e7111e402e617d0de57b55e3799207b07/MHG-LAB/api" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/MHG-LAB/api">api/api.js at main · MHG-LAB/api</a></strong></div><div>搜集到的一些古古怪怪的小玩意儿~~. Contribute to MHG-LAB/api development by creating an account on GitHub.</div></blockquote>

**Comment by MHuiG** [comment]
@xaoxuu https://source.unsplash.com 这个API似乎也即将被弃用 http://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html

<blockquote><div><strong><a href="https://source.unsplash.com/">Unsplash Image API | Free HD Photo API</a></strong></div><div>
    
  Create with the largest collection of high-quality images that are free to use. Trusted by Trello, Medium, and thousands of other API applications to power their free picture needs.

</div></blockquote>
<blockquote><div>Unsplash API Changelog</div><div><strong><a href="/deprecations/2021/11/25/source-deprecation.html">Unsplash Source being deprecated</a></strong></div><div>Unsplash Source is being deprecated. Existing uses will continue to work, however for new projects use the full Unsplash API.</div></blockquote>

**Comment by xaoxuu** [comment]
新的API似乎都得用token了，有没有原来这种替代方案？
```
https://source.unsplash.com/2000x400/?code
```
访问就直接得到可以用的图片： https://source.unsplash.com/2000x400/?code

**Comment by xaoxuu** [comment]
如果没有现成的接口的话，我能想到的办法就是自己写一个vercel来调用并返回图片
