### ISSUE TITLE
【建议】：开启阅读模式后copyright组件过宽

### ISSUE THREAD

**Issue by BeaCox** [xaoxuu/hexo-theme-volantis#779]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

![](https://p.qlogo.cn/hy_personal/3e28f14aa05168425df86a54e11e2eba9e233204c8cea7da9a618ef059ed7999/0.png)
<br>如图，开启阅读模式后，copyright组件布局过宽。希望能修改一下样式。

### 参考链接

<https://bowenyoung.cn/posts/sqli3/>
开启阅读模式

**Comment by Tikas** [comment]
哇，这个版权声明样式竟然上线了，好喜欢

**Comment by BeaCox** [comment]
> 哇，这个版权声明样式竟然上线了，好喜欢

雀食好看
