### ISSUE TITLE
【问题】：上下滚动文章懒加载怎么关闭

### ISSUE THREAD

**Issue by qiudaoermu** [xaoxuu/hexo-theme-volantis#781]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.0.0

### 复现地址

http://localhost:4000/2022/undefined/20/%F0%9F%93%A3%F0%9F%93%A3ph-d-vs-Engineer/?cache-bust=1656687254940

### 问题描述

文章上下滚动，有白屏，感觉是懒加载之类的，请问这个怎么关闭
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/13454418/177234126-4475991f-0930-472f-8799-fc7c5d91373b.png">

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
没有修改
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
没有修改
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
v14.8.0
6.14.7
```

</p></details>

<details><summary>package.json</summary><p>

```
bquote>
```

</p></details>

**Comment by BeaCox** [comment]
在`_config.volantis.yml`中配置：
```yml
plugins:
  scrollreveal:
    enable: false
```

**Comment by qiudaoermu** [comment]
> 

不起作用啊
