### ISSUE TITLE
仿照btf的cdn配置方法

### ISSUE THREAD

**Issue by imjason** [xaoxuu/hexo-theme-volantis#786]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

1统一配置cdn链接
2统一配置cdn前缀(支持一下cdnjs)
3把主题相关静态资源提交cdnjs

### 参考链接
https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/_config.yml#L877

**Comment by imjason** [comment]
由于elemecdn关闭了回源，需要更好的cdn解决方案

**Comment by Tikas** [comment]
由于 cdnjs 不支持个人仓加速，增加 cdnjs ，首先考虑 cdn 会与个人仓 cdn 冲突。

在现有功能作改进时，就需要为 cdn 划分出公共仓和个人仓 cdn 加速，才能避免统一 cdn 设置格式导致两者之间的冲突

**Comment by imjason** [comment]
所以我觉得btf的解决方案很好
