### ISSUE TITLE
【建议】：root配置后，css文件找不到

### ISSUE THREAD

**Issue by fightinggg** [xaoxuu/hexo-theme-volantis#793]
### 检查清单

- [x] 已经搜索过，没有发现类似 issue。
- [x] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

![image](https://user-images.githubusercontent.com/42932982/181905167-6f378c00-1bcd-44d5-afc9-298d770cba46.png)

![image](https://user-images.githubusercontent.com/42932982/181905197-870ae3ba-c813-4d6f-9c97-f0fe8778d69c.png)

**Comment by MHuiG** [comment]
我没试过，我猜路径需要以反斜杠结尾 /a/

**Comment by fightinggg** [comment]
> 我没试过，我猜路径需要以反斜杠结尾 /a/

刚刚试过了，不生效

**Comment by MHuiG** [comment]
或者是这里的问题

https://github.com/volantis-x/hexo-theme-volantis/blob/dev/_config.yml#L55

<blockquote><img src="https://repository-images.githubusercontent.com/108073634/e60b3434-53b7-463d-9a7f-a0e1f5723368" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo https://vlts.cc  https://volantis.js.org - hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis</div></blockquote>

**Comment by fightinggg** [comment]
> 或者是这里的问题
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/dev/_config.yml#L55
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/108073634/e60b3434-53b7-463d-9a7f-a0e1f5723368"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis](https://github.com/volantis-x/hexo-theme-volantis)**A Wonderful Theme for Hexo https://vlts.cc  https://volantis.js.org - hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis

刚刚试了一下，确实是这里的问题，有其他不需要用户做额外配置的办法吗

<blockquote><img src="https://repository-images.githubusercontent.com/108073634/e60b3434-53b7-463d-9a7f-a0e1f5723368" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo https://vlts.cc  https://volantis.js.org - hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis</div></blockquote>
<blockquote><img src="https://unpkg.com/volantis-static@0.0.1654736714924/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://unpkg.com/volantis-static@0.0.1649552113628/media/org.volantis/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/">Volantis</a></strong></div><div>Volantis 是一个功能丰富、高度模块化的 Hexo 博客主题。得益于其强大的模块化特性，您可以轻松搭建一个极简风格的博客，也可以仿照官网搭建一个多人协作的、包含文档模块的大体量综合型博客。</div></blockquote>
<blockquote><img src="https://unpkg.com/volantis-static@0.0.1654736714924/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://unpkg.com/volantis-static@0.0.1649552113628/media/org.volantis/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/">Volantis</a></strong></div><div>Volantis 是一个功能丰富、高度模块化的 Hexo 博客主题。得益于其强大的模块化特性，您可以轻松搭建一个极简风格的博客，也可以仿照官网搭建一个多人协作的、包含文档模块的大体量综合型博客。</div></blockquote>

**Comment by MHuiG** [comment]
有的，直接删掉这一行就是自动配置

写上这一行就把自动配置覆盖了

**Comment by fightinggg** [comment]
> 有的，直接删掉这一行就是自动配置
> 
> 写上这一行就把自动配置覆盖了

这个文件在主题文件夹下，用户的配置里面没有这个文件

**Comment by MHuiG** [comment]
有一个技巧
新建一个 _config.volantis.yml 文件覆盖主题的配置

https://github.com/volantis-x/community/blob/main/_config.volantis.yml

<blockquote><img src="https://opengraph.githubassets.com/c7bbd881f0e378fd02e285256017cde8176a4cafd0b6bcc2baf36cf54d231f80/volantis-x/community" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/community">community/_config.volantis.yml at main · volantis-x/community</a></strong></div><div>Volantis Community 社区主页 https://vlts.cc https://volantis.js.org - community/_config.volantis.yml at main · volantis-x/community</div></blockquote>

**Comment by fightinggg** [comment]
> 有一个技巧 新建一个 _config.volantis.yml 文件覆盖主题的配置
> 
> https://github.com/volantis-x/community/blob/main/_config.volantis.yml
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ace8abe6de8835d12c09ffec24a63f4242fcba6f0fe2388f148f59445a7db6c5/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f633762626438383166306533373866643032653238353235363031376364653831373661346361666430623662636332626166333663663534643233316638302f766f6c616e7469732d782f636f6d6d756e697479"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[community/_config.volantis.yml at main · volantis-x/community](https://github.com/volantis-x/community)**Volantis Community 社区主页 https://vlts.cc https://volantis.js.org - community/_config.volantis.yml at main · volantis-x/community

可以，但是建议把主题文件夹里面的默认配置改一下

<blockquote><img src="https://opengraph.githubassets.com/c7bbd881f0e378fd02e285256017cde8176a4cafd0b6bcc2baf36cf54d231f80/volantis-x/community" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/community">community/_config.volantis.yml at main · volantis-x/community</a></strong></div><div>Volantis Community 社区主页 https://vlts.cc https://volantis.js.org - community/_config.volantis.yml at main · volantis-x/community</div></blockquote>
<blockquote><img src="https://unpkg.com/volantis-static@0.0.1654736714924/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://unpkg.com/volantis-static@0.0.1649552113628/media/org.volantis/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/">Volantis</a></strong></div><div>Volantis 是一个功能丰富、高度模块化的 Hexo 博客主题。得益于其强大的模块化特性，您可以轻松搭建一个极简风格的博客，也可以仿照官网搭建一个多人协作的、包含文档模块的大体量综合型博客。</div></blockquote>
<blockquote><img src="https://unpkg.com/volantis-static@0.0.1654736714924/media/org.volantis/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://unpkg.com/volantis-static@0.0.1649552113628/media/org.volantis/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/">Volantis</a></strong></div><div>Volantis 是一个功能丰富、高度模块化的 Hexo 博客主题。得益于其强大的模块化特性，您可以轻松搭建一个极简风格的博客，也可以仿照官网搭建一个多人协作的、包含文档模块的大体量综合型博客。</div></blockquote>

**Comment by MHuiG** [comment]
改完了，再看一下

**Comment by MHuiG** [comment]
这个等6.0重构一下，

谁帮我回滚一下commit（

**Comment by fightinggg** [comment]
> 这个等6.0重构一下，
> 
> 谁帮我回滚一下commit（

为啥通过加载主题源码构建出的blog，css文件不太一样，中间多了个数字，看看这个是不是同一个原因
![image](https://user-images.githubusercontent.com/42932982/181906678-eda733d1-2ec9-4dcd-a93f-a758cd030961.png)

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/dev/_config.yml#L59

cdn_version: false

<blockquote><img src="https://repository-images.githubusercontent.com/108073634/e60b3434-53b7-463d-9a7f-a0e1f5723368" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo https://vlts.cc  https://volantis.js.org - hexo-theme-volantis/_config.yml at dev · volantis-x/hexo-theme-volantis</div></blockquote>
