### ISSUE TITLE
新增一个浏览量模块

### ISSUE THREAD

**Issue by imjason** [xaoxuu/hexo-theme-volantis#797]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

直接使用的leancloud浏览量已经失效了，但是waline提供了一个浏览量记录的接口，可以使用

### 参考链接

https://waline.js.org/guide/client/pageview.html#单独使用

**Comment by Colsrch** [comment]
主题支持 `leancloud`、`busuanzi`、`waline`、`twikoo`、`discuss`、`artalk` 进行页面访问统计。
其中，`leancloud` 与 `busuanzi` 在 `analytics` 下配置。
其它统计工具请在对应配置项下启用，并注释 `analytics` 下所有配置。

> 注意：使用评论系统提供的统计时，需要启用对应评论系统

https://volantis.js.org/v5/advanced-settings/#PV-%E5%92%8C-UV

**Comment by imjason** [comment]
经过询问waline作者，waline支持全站统计pv，但是不支持uv，可以添加一下吗

```
<span class="waline-pageview-count" data-path="全站" />
```
在首页可以仅引入单统计版
