### ISSUE TITLE
【问题】：volantis v5.7.4出现配置文件检查失败的错误 dev分支

### ISSUE THREAD

**Issue by zehuajun** [xaoxuu/hexo-theme-volantis#801]
### 检查清单

- [x] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.7.4

### 复现地址

没有

### 问题描述

出现
============================================================
配置文件检查失败！| Configuration check failed!
============================================================
description 未配置！
请在站点配置 _config.yml 中配置 description
description主要用于SEO，告诉搜索引擎一个关于您站点的简单描述，通常建议在其中包含您网站的关键词。
see: https://hexo.io/zh-cn/docs/configuration
description is not configured!
============================================================
/data/data/com.termux/files/home/hexo/themes/volantis/scripts/events/lib/check-environment.js:71
  throw new Error('配置文件检查失败！| Configuration check failed!');
  ^

Error: 配置文件检查失败！| Configuration check failed!
    at CheckConfError (/data/data/com.termux/files/home/hexo/themes/volantis/scripts/events/lib/check-environment.js:71:9)
    at /data/data/com.termux/files/home/hexo/themes/volantis/scripts/events/lib/check-environment.js:38:17
    at ChildProcess.exithandler (node:child_process:402:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

问题

主题安装操作

在themes目录中运行

git clone https://github.com/volantis-x/hexo-theme-volantis.git

mv hexo-theme-volantis volantis

cd ..

vim _config.yml

theme:volantis

然后运行hexo g就出现错误
![Screenshot_20220816_142315_com termux](https://user-images.githubusercontent.com/87254340/184811679-9b10c723-fe84-452d-89e4-acd47e81b686.jpg)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```
deploy:
  type: git
  repo: git@github.com:………………
  branch: master
</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```
v18.7.0
8.15.0
</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```
home@ /data/data/com.termux/files/home
├── a-sync-waterfall@1.0.1 extraneous
├── abbrev@1.1.1 extraneous
├── ansi-regex@5.0.1 extraneous
├── ansi-styles@4.3.0 extraneous
├── anymatch@3.1.2 extraneous
├── archy@1.0.0 extraneous
├── argparse@2.0.1 extraneous
├── asap@2.0.6 extraneous
├── binary-extensions@2.2.0 extraneous
├── bluebird@3.7.2 extraneous
├── braces@3.0.2 extraneous
├── camel-case@4.1.2 extraneous
├── chalk@4.1.2 extraneous
├── chokidar@3.5.3 extraneous
├── color-convert@2.0.1 extraneous
├── color-name@1.1.4 extraneous
├── command-exists@1.2.9 extraneous
├── commander@5.1.0 extraneous
├── cross-spawn@7.0.3 extraneous
├── cuid@2.1.8 extraneous
├── deepmerge@4.2.2 extraneous
├── dom-serializer@1.4.1 extraneous
├── domelementtype@2.3.0 extraneous
├── domhandler@4.3.1 extraneous
├── domutils@2.8.0 extraneous
├── entities@3.0.1 extraneous
├── esprima@4.0.1 extraneous
├── fast-equals@3.0.3 extraneous
├── fill-range@7.0.1 extraneous
├── function-bind@1.1.1 extraneous
├── glob-parent@5.1.2 extraneous
├── graceful-fs@4.2.10 extraneous
├── has-flag@4.0.0 extraneous
├── has@1.0.3 extraneous
├── hexo-cli@4.3.0 extraneous
├── hexo-front-matter@3.0.0 extraneous
├── hexo-fs@3.1.0 extraneous
├── hexo-i18n@1.0.0 extraneous
├── hexo-log@3.1.0 extraneous
├── hexo-util@2.7.0 extraneous
├── hexo@6.2.0 extraneous
├── highlight.js@11.6.0 extraneous
├── htmlparser2@7.2.0 extraneous
├── inherits@2.0.4 extraneous
├── is-binary-path@2.1.0 extraneous
├── is-core-module@2.10.0 extraneous
├── is-extglob@2.1.1 extraneous
├── is-glob@4.0.3 extraneous
├── is-number@7.0.0 extraneous
├── is-plain-object@5.0.0 extraneous
├── isexe@2.0.0 extraneous
├── js-yaml-js-types@1.0.0 extraneous
├── js-yaml@4.1.0 extraneous
├── jsonparse@1.3.1 extraneous
├── lower-case@2.0.2 extraneous
├── micro-memoize@4.0.11 extraneous
├── micromatch@4.0.5 extraneous
├── min-indent@1.0.1 extraneous
├── minimist@1.2.6 extraneous
├── moize@6.1.1 extraneous
├── moment-timezone@0.5.34 extraneous
├── moment@2.29.4 extraneous
├── no-case@3.0.4 extraneous
├── normalize-path@3.0.0 extraneous
├── nunjucks@3.2.3 extraneous
├── pascal-case@3.1.2 extraneous
├── path-key@3.1.1 extraneous
├── path-parse@1.0.7 extraneous
├── picocolors@1.0.0 extraneous
├── picomatch@2.3.1 extraneous
├── pretty-hrtime@1.0.3 extraneous
├── prismjs@1.28.0 extraneous
├── readable-stream@3.6.0 extraneous
├── readdirp@3.6.0 extraneous
├── resolve@1.22.1 extraneous
├── rfdc@1.3.0 extraneous
├── rxjs@7.5.6
├── safe-buffer@5.2.1 extraneous
├── shebang-command@2.0.0 extraneous
├── shebang-regex@3.0.0 extraneous
├── sprintf-js@1.1.2 extraneous
├── string_decoder@1.3.0 extraneous
├── strip-ansi@6.0.1 extraneous
├── strip-indent@3.0.0 extraneous
├── supports-color@7.2.0 extraneous
├── supports-preserve-symlinks-flag@1.0.0 extraneous
├── text-table@0.2.0 extraneous
├── through2@4.0.2 extraneous
├── tildify@2.0.0 extraneous
├── titlecase@1.1.3 extraneous
├── to-regex-range@5.0.1 extraneous
├── util-deprecate@1.0.2 extraneous
├── warehouse@4.0.2 extraneous
└── which@2.0.2 extraneous
</p></details>

**Comment by zehuajun** [comment]
在删除themes目录中的volantis文件夹后运行

cd ..
反回上级目录后

运行npm i hexo-theme-volantis命令后
运行hexo g
出现一样的错误

============================================================
配置文件检查失败！| Configuration check failed!
============================================================
description 未配置！
请在站点配置 _config.yml 中配置 description
description主要用于SEO，告诉搜索引擎一个关于您站点的简单描述，通常建议在其中包含您网站的关键词。
see: https://hexo.io/zh-cn/docs/configuration
description is not configured!
============================================================
/data/data/com.termux/files/home/hexo/node_modules/hexo-theme-volantis/scripts/events/lib/check-environment.js:71
  throw new Error('配置文件检查失败！| Configuration check failed!');
  ^

Error: 配置文件检查失败！| Configuration check failed!
    at CheckConfError (/data/data/com.termux/files/home/hexo/node_modules/hexo-theme-volantis/scripts/events/lib/check-environment.js:71:9)
    at /data/data/com.termux/files/home/hexo/node_modules/hexo-theme-volantis/scripts/events/lib/check-environment.js:38:17
    at ChildProcess.exithandler (node:child_process:402:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Node.js v18.7.0

但目录不同

错误如图

![Screenshot_20220816_143031_com termux](https://user-images.githubusercontent.com/87254340/184812718-f4e724cc-9f6b-43b8-9320-4da827f9eb54.jpg)


<blockquote><div><img src="/icon/favicon-32x32.png" height="14"> Hexo</div><div><strong><a href="https://hexo.io/zh-cn/docs/configuration">配置</a></strong></div><div>您可以在 _config.yml 中修改大部分的配置。   网站   参数 描述    title 网站标题   subtitle 网站副标题   description 网站描述   keywords 网站的关键词。支持多个关键词。   author 您的名字   language 网站使用的语言。对于简体中文用户来说，使用不同的主题可能需要设置成不同的值，请参考你的主题的文档自行设置，常见的有</div></blockquote>

**Comment by zehuajun** [comment]
感谢，我已经解决了这个问题
Thank you. I have solved this problem

**Comment by so1ve** [comment]
有没有一种可能 报错是中文的

**Comment by Colsrch** [comment]
有没有一种可能 报错是中文的
![image](https://user-images.githubusercontent.com/58458181/184814555-265b9fa3-53b2-47f1-b3bd-6202463984c7.png)

**Comment by zehuajun** [comment]
报错就是中文
我还傻乎乎的在主题配置文件里找
