### ISSUE TITLE
【建议】：好喜欢这种图表显示方式，不知道可否增加此功能

### ISSUE THREAD

**Issue by Tikas** [xaoxuu/hexo-theme-volantis#810]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

无意之中，发现一个非常不错的图表显示页面，有三种方式，由于还在学习 CSS，不知道此功能是否插件完成，还是需要其他功能来实现

作者也是使用 hexo 来实现的

### 参考链接

https://blog.xmwpro.com/echarts/

**Comment by Tikas** [comment]
为防止作者更改文章，在此补充效果图：

![image](https://user-images.githubusercontent.com/3396710/189804091-9ccde02a-ff61-44c6-bac6-8c0197f6f074.png)

![image](https://user-images.githubusercontent.com/3396710/189804112-429f5e35-ad77-4ef3-8f6f-aba78f2738c6.png)

![image](https://user-images.githubusercontent.com/3396710/189804141-a4989984-2d7c-4e51-9301-357ec3ffc87e.png)

**Comment by qmmm61** [comment]
echarts而已，关了吧

**Comment by Tikas** [comment]
太强了，原来链接里就是这货，有需要时，再来了解了解
