### ISSUE TITLE
【建议】：改进Artalk插件的黑暗模式？

### ISSUE THREAD

**Issue by UptonEdward** [xaoxuu/hexo-theme-volantis#815]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

Artalk的黑暗模式和主题的黑暗模式不同步。

1. 在Artalk前端打开黑暗模式，同时在Volentis关闭黑暗模式，刷新后Artalk评论框会变成夜间模式，再次给Volentis打开黑暗模式之后恢复正常。

2. 在Artalk前端关闭黑暗模式，同时在Volentis打开黑暗模式，刷新后Artalk评论框会变成日间模式，再次给Volentis关闭黑暗模式之后恢复正常。

问题这个出现的博客页面已经贴在参考链接了，希望开发者看一下，不知道可不可以进行一下优化捏。

### 参考链接

https://blog.shupl.icu/2022/10/02/hello-world/

**Comment by inkss** [comment]
> 在Artalk前端打开黑暗模式

您是指在 Artalk 控制中心的设置中，勾选了（过）前端配置中的暗黑模式吗？如果是如此，请留意配置文件中相关注释。

https://github.com/volantis-x/hexo-theme-volantis/blob/c4ac13c37392b478fffd89e8b8cef6f76766f9dd/_config.yml#L402-L404

**`darkMode`（暗黑模式）为不建议用户覆写的前端配置项目。**

请检查您的 Artalk 配置文件（artalk-go.yml），确保 `frontend` 一节中不出现 `darkMode` 相关内容。
