### ISSUE TITLE
【问题】：文章目录存在bug

### ISSUE THREAD

**Issue by 289373410** [xaoxuu/hexo-theme-volantis#824]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://www.aquestian.cn/blogs/docker%E9%83%A8%E7%BD%B2jar%E5%8C%85%E5%B9%B6%E5%AE%9E%E7%8E%B0%E9%95%9C%E5%83%8F%E8%BF%81%E7%A7%BB/

### 问题描述

多次点击文章目录，相邻且同级的文章目录，会出现反复跳页的情况出现，观察了源码使用了递归，这里是不是不太合理。您如有邮箱，我将把这个bug以视频的方式发给您。

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by Tikas** [comment]
在复现地址里，本文的目录如下：

+ 说明
+ 实例
+ 镜像迁移

bug 实现：

点击实例，再点说明，再点实例，再点说明

以上步骤操作快些

此时，理论上文本应该定位在 【说明】 里，实际会跳回 【实例】

此时 BUG 影响还不大，但是，但是来了：

再偶然的另一次尝试 BUG 复现时，触发了无限两个目录之间来回跳动！

是无限来回！

此 BUG 非常严重！

**Comment by Tikas** [comment]
无限来回触发：

经多次复现，在快速顺序点击目录时，如： 3、2、1，再点  2，此时会很容易触发无限来回目录定位

**Comment by lete114** [comment]
为什么用js来做滚动？而不用一行 css 来做滚动？
`scroll-behavior: smooth;`

**Comment by 289373410** [comment]
66666 解决速度杠杠的！
