### ISSUE TITLE
【反馈】：页面底部访问量无法正常显示

### ISSUE THREAD

**Issue by ning0818** [xaoxuu/hexo-theme-volantis#830]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [ ] 主题官网也存在这个问题。

### 复现地址

www.yuanning0818.tk

### 复现步骤

什么都没动，访问量一直不现显示

### 配置文件

analytics: >
    <span>本站总访问量为 <span id='busuanzi_value_site_pv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span>访客数为 <span id='busuanzi_value_site_uv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
  # site copyright

### 环境信息

我是集成部署

**Comment by ning0818** [comment]
已修复，加了一句<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"

**Comment by BeaCox** [comment]
你说的

> 发现配置里的和官网的不一样

是因为Volantis已经集成功能，你只需要配置js文件url，并开启busuanzi即可
你的配置文件中并没有开启busuanzi导致js没有引入，故无法显示访问量，如下图：
![配置文件截图](https://kjimg10.360buyimg.com/ott/jfs/t1/92034/39/35382/1287/638b026fE68799ffa/1eaefb5d399074c1.png)

将#去掉，开启busuanzi即可，因此并不是bug

**Comment by Tikas** [comment]
能提问是好事的，我们鼓励多提问，但是，我们更提倡，提问前先多看看文档和网上找找答案。

感谢对 volantis 的支持
