### ISSUE TITLE
【问题】：博客首页很正常，但是每篇博文点进去都是一片空白

### ISSUE THREAD

**Issue by ning0818** [xaoxuu/hexo-theme-volantis#832]
### 检查清单

- [x] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://www.yuanning0818.tk/

### 问题描述

我只是在package.json里面加了点rss的配置

### 配置文件

package.json

{
 "name": "hexo-site",
 "version": "0.0.0",
 "private": true,
 "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
 "hexo": {
    "version": "6.2.0"
  },
 "dependencies": {
    "@jridgewell/gen-mapping": "^0.3.2",
    "@jridgewell/resolve-uri": "^3.1.0",
    "@jridgewell/set-array": "^1.1.2",
    "@jridgewell/source-map": "^0.3.2",
    "@jridgewell/sourcemap-codec": "^1.4.14",
    "@jridgewell/trace-mapping": "^0.3.17",
    "hexo": "^6.3.0",
    "hexo-algoliasearch": "^1.0.0",
    "hexo-autoprefixer": "^2.0.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-seo-friendly-sitemap": "^0.2.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-pdf": "^1.1.1",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-uuid": "^1.0.2",
    "hexo-wordcount": "^6.0.1",
    "moment-timezone": "^0.5.39",
    "speech-rule-engine": "^4.0.7"
  },
 "devDependencies": {
    "gulp": "^4.0.2",
    "gulp-clean-css": "^4.3.0",
    "gulp-html-minifier-terser": "^6.0.1",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-minify-css": "^1.2.4",
    "gulp-sourcemaps": "^3.0.0",
    "gulp-terser": "^2.1.0",
    "gulp-uglify": "^3.0.2",
    "inline-csp-hash": "^1.1.16"
  }
}

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by ning0818** [comment]
但是我把后加的那一段package.json代码删掉之后就好了，这是为什么呢？

**Comment by Tikas** [comment]
最后的是那一段？

是 `}` 吗？

**Comment by ning0818** [comment]
我是把历史记录还原到了没加配置前备份的package.json，然后就好了
原来是这样
`{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.2"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-wordcount": "^6.0.1"
  }
}
`

加完是上面那样
