### ISSUE TITLE
【反馈】：busuanzi已经开启了，但还是不显示访问量

### ISSUE THREAD

**Issue by ning0818** [xaoxuu/hexo-theme-volantis#833]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [ ] 主题官网也存在这个问题。

### 复现地址

www.yuanning0818.tk

### 复现步骤

和上次差不多，把busuanzi的true前面的注释去掉了，去掉之后侧面的访问量显示了，可是页面底部的访问量又不显示了
![image](https://user-images.githubusercontent.com/117955401/206346586-72dda022-e3dd-44fe-a70f-0d2a762a48c9.png)
![image](https://user-images.githubusercontent.com/117955401/206346703-8be17bd9-f162-4c50-9707-8344b21cad20.png)
![image](https://user-images.githubusercontent.com/117955401/206346736-495e1368-a435-4530-8c3b-a12aa06543af.png)
![image](https://user-images.githubusercontent.com/117955401/206346843-3f30a429-fe22-430f-871d-2eb42b2f6f77.png)

### 配置文件

<details><summary>主题配置文件</summary><p>

```yml
<span>本站总访问量为 <span id='busuanzi_value_site_pv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span>访客数为 <span id='busuanzi_value_site_uv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
```
```yml
busuanzi:
    enable: true
```
</p></details>

### 环境信息

<details><summary>暂无</summary><p>

</p></details>

**Comment by inkss** [comment]
如您所见，不蒜子使用的为 ID 选择器，原则上页面中应该只出现一处，建议仅保留一个全站访问量统计显示。

**Comment by ning0818** [comment]
but，https://www.yt-blog.top，为什么他就显示了两个地方？

**Comment by BeaCox** [comment]
> 那你去看看，[https://www.yt-blog.top，为什么他就显示了两个地方？](https://www.yt-blog.top%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BB%96%E5%B0%B1%E6%98%BE%E7%A4%BA%E4%BA%86%E4%B8%A4%E4%B8%AA%E5%9C%B0%E6%96%B9%EF%BC%9F)

已查看该网站，下面为你解答：
1. 首先，该博主能在两处显示是由于他引入了新的js，如下图：
<details>
<summary>点击查看图片</summary>
<img src="https://kjimg10.360buyimg.com/ott/jfs/t1/185600/6/33854/843615/63928099E40f3b0fc/d8911a06ffdf61e8.png">
<img src="https://kjimg10.360buyimg.com/ott/jfs/t1/78984/39/16428/281789/639280abE9e3f6c0f/909c57b1a7b1a6d4.jpg"></details>
显然，这两处访问量/访客数对应的id是不一样的。其中，侧边栏用的是busuanzi，而页脚他引入了<https://unpkg.com/qexo-static@1.3.0/hexo/statistic/statistic.js>用来在页脚显示访问量，明显可以看出两处访问量数值也不一样。这是该博主自定义的内容而非主题自带功能，若你也想实现和该博主一样的效果，请咨询博主本人，解决自定义问题不是主题维护人员的义务。

2. 关于`bug-report`
感谢你的反馈！我们在文档中没有提到不应当在侧边栏和页脚同时显示访问量，我们将会及时更新文档。但我认为两处同时显示的确是一种冗余，因此不会进行功能上的改动。

3. 关于沟通
我不是xaoxuu、柚子、MHuiG那样负责主题开发的大佬，但我尽我所能地为大家解决问题。但我更希望的是，在提问之前，先确人自己在文档、官网开源仓库配置文件等地方都找不到解决办法。另外，我也希望我们能够平等地交流。
> 上次就是这样的问题
那你去看看

这样的措辞，私以为不是很好的提问措辞。可以理解你无法解决问题的心情，但请放平心态。开源项目的发展需要毅力、更离不开互相尊重。

再次感谢你的反馈和对Volantis的支持，祝好！

**Comment by ning0818** [comment]
> 

sorry

**Comment by ning0818** [comment]
> > but，[https://www.yt-blog.top，为什么他就显示了两个地方？](https://www.yt-blog.top%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BB%96%E5%B0%B1%E6%98%BE%E7%A4%BA%E4%BA%86%E4%B8%A4%E4%B8%AA%E5%9C%B0%E6%96%B9%EF%BC%9F)
> 
> 已查看该网站，下面为你解答：
> 
> 1. 首先，该博主能在两处显示是由于他引入了新的js，如下图：
> 
> 点击查看图片
> ![](https://camo.githubusercontent.com/d1029eed1ab2fb669a2e792ea631ccc9fb140d9cdd29e7c5f26eca8a1468db85/68747470733a2f2f6b6a696d6731302e333630627579696d672e636f6d2f6f74742f6a66732f74312f3138353630302f362f33333835342f3834333631352f36333932383039394534306633623066632f643839313161303666666466363165382e706e67) ![](https://camo.githubusercontent.com/145f9192363ffff9c7225bb5e18a7fc30830fb79a8961c4a264655c270215db5/68747470733a2f2f6b6a696d6731302e333630627579696d672e636f6d2f6f74742f6a66732f74312f37383938342f33392f31363432382f3238313738392f36333932383061624539653366366330662f393039633537623161376231613664342e6a7067)
> 显然，这两处访问量/访客数对应的id是不一样的。其中，侧边栏用的是busuanzi，而页脚他引入了用来在页脚显示访问量，明显可以看出两处访问量数值也不一样。这是该博主自定义的内容而非主题自带功能，若你也想实现和该博主一样的效果，请咨询博主本人，解决自定义问题不是主题维护人员的义务。
> 2. 关于`bug-report`
>    感谢你的反馈！我们在文档中没有提到不应当在侧边栏和页脚同时显示访问量，我们将会及时更新文档。但我认为两处同时显示的确是一种冗余，因此不会进行功能上的改动。
> 3. 关于沟通
>    我不是xaoxuu、柚子、MHuiG那样负责主题开发的大佬，但我尽我所能地为大家解决问题。但我更希望的是，在提问之前，先确人自己在文档、官网开源仓库配置文件等地方都找不到解决办法。另外，我也希望我们能够平等地交流。
> 
> > 上次就是这样的问题
> > 那你去看看
> 
> 这样的措辞，私以为不是很好的提问措辞。可以理解你无法解决问题的心情，但请放平心态。开源项目的发展需要毅力、更离不开互相尊重。
> 
> 再次感谢你的反馈和对Volantis的支持，祝好！

我和他正闹矛盾呢...
