### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dc932dc** [xaoxuu/hexo-theme-volantis#835]

**Comment by Tikas** [comment]
这个预加载动画，可以做的效果就太广泛了，不仅仅限于进度条。

而每个人的需求又不一样，真增加，可得分：文字、图片、SVG 动画等等。

而不同风格又要考虑颜色搭配等，中性灰反而会成为比较理想的统一背景色调。

真增加，小而美才是核心，毕竟能加载前有个过场画面是会吸引用户停留，而如果过场画面太臃肿，导致页面压缩大于 14kb，就会增加传输量。

**Comment by Tikas** [comment]
开发者们目前在完善 6.0 功能模块，如果可以，您可以提交 Pr, 参与进来，更甚至可以专门维护开场画画这一板块

这样以后这个板块的相关维护，都会交给你来负责，专人做专事

**Comment by Tikas** [comment]
能站在自己的需求上提问，这是好的

能站在用户的需求上开发，这才更好

开发时增加一个功能，不仅仅是考虑单一使用场景，还要考虑到更多的用户使用场景，这样才能覆盖更多的用户，而如何用最小的代码量最高效去实现，这才是真谛。
