### ISSUE TITLE
【建议】：可否在_config.yml添加Artitalk.js自定义图床选项？

### ISSUE THREAD

**Issue by amrice** [xaoxuu/hexo-theme-volantis#836]
### 检查清单

- [ ] 已经搜索过，没有发现类似 issue。
- [ ] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

在使用Artitalk.js时发现无法上传图片，API接口传回404，翻了一下文档发现是图床官方更换了接口，看到该项目在8月份有人提交了[Issue](https://github.com/ArtitalkJS/Artitalk/issues/106)，但是迄今为止无人回应，所以能不能在本项目的配置文件中Artitalk字段添加自定义图床API选项？

**Comment by BeaCox** [comment]
去Artitalk仓库看了一眼，已经很久没有维护了。
关于自定义图床API，是Artitalk自身没有这个功能，并不是volantis没有提供相应配置。
可以参考这个[issue](https://github.com/ArtitalkJS/Artitalk/issues/67)，Artitalk的作者提到了为什么没有实现自定义图床的原因，看样子也不会去实现了......
解决办法：
1. 给Artitalk提issue，看作者有没有改变想法（不太可能）
2. 联系官方图床提供者[杜老师](https://dusays.com)，看看杜老师是否继续免费为Artitalk提供图床，并在Artalk.js中更换接口地址（不太合适）
3. 自己给Artitalk提PR，实现自定义图床功能，等待作者merge（看作者什么时候在了）
4. 利用picgo、sharex等工具，上传图片至图床并复制图片markdown，粘贴到说说中（最可能实现）
