### ISSUE TITLE
【问题】：6.0-pjax版本Artalk评论系统不适配主题darkmode

### ISSUE THREAD

**Issue by wndbac** [xaoxuu/hexo-theme-volantis#852]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [ ] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://wndbac.cn

### 问题描述

当`6.0-pjax`版本开启darkmode，Artalk评论系统可能会出现不适配的情况，如下图所示：
![image](https://user-images.githubusercontent.com/97789192/213716186-029ebf84-d041-41a9-850b-7274fec22a1f.png)
复现方法，打开darkmode，再刷线网页，即可实现

**Comment by ByuNyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
