### ISSUE TITLE
【问题】：不蒜子统计每一篇文章访问量都是共享的

### ISSUE THREAD

**Issue by seepine** [xaoxuu/hexo-theme-volantis#858]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 问题描述

不管访问哪一篇文章，其访问数增加都是共享计数

**Comment by Tikas** [comment]
看了一下复现地址，已经没有这个问题，再看大佬已经提交修复 pr，太强了，这一段操作让我这个不懂网站开发的人，实在佩服，我想问问，大佬有没有什么秘技，因为我也在学网站开发，刚刷完 CSS 教程

**Comment by seepine** [comment]
> 看了一下复现地址，已经没有这个问题，再看大佬已经提交修复 pr，太强了，这一段操作让我这个不懂网站开发的人，实在佩服，我想问问，大佬有没有什么秘技，因为我也在学网站开发，刚刷完 CSS 教程

我没有修复，看了下不蒜子是个人维护，想了下还是怕跑路，提交个工单，然后换回leancloud了，提pr的是leancloud另一个问题 #860

我不是大佬主业不是前端，不过前端相对比较简单易学，只做博客学js css dom操作等等就够了，如果要当成职业，需要再学ts vue react 之流

**Comment by Tikas** [comment]
不听不听，我不听，大佬果然低调，我懂得

**Comment by inkss** [comment]
能否再复现下

**Comment by seepine** [comment]
> 能否再复现下

直接克隆5.7.7的demo，开启busuanzi统计，就是这个问题了，每篇访问量都共享

**Comment by ghost** [comment]
主题所用的默认js有问题，换成busuanzi官网的js就解决。[参考文章](https://github.com/liuyib/hexo-theme-stun/issues/185)
