### ISSUE TITLE
【反馈】：使用评论twikoo作为浏览数统计时，并没有显示数字

### ISSUE THREAD

**Issue by seepine** [xaoxuu/hexo-theme-volantis#859]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [X] 主题官网也存在这个问题。

### 复现步骤

![image](https://user-images.githubusercontent.com/93666053/227767766-7c0ce34d-dea9-480b-99bf-f7bd80eb6aec.png)
评论是正常的说明twikoo服务连得上，但是访问量不显示

### 配置文件

![image](https://user-images.githubusercontent.com/93666053/227767801-8f6ee9bb-776c-41db-a930-a6a31838b959.png)
取消所有

### 环境信息

volantis v5.7.7

**Comment by inkss** [comment]
这里的配置和它无关，可以先看看 v6 版本的文档：[分析与统计](https://volantis.js.org/v6/advanced-settings/?keyword=%E8%AE%A1%E6%95%B0#%E5%88%86%E6%9E%90%E4%B8%8E%E7%BB%9F%E8%AE%A1)

**Comment by seepine** [comment]
> 这里的配置和它无关，可以先看看 v6 版本的文档：[分析与统计](https://volantis.js.org/v6/advanced-settings/?keyword=%E8%AE%A1%E6%95%B0#%E5%88%86%E6%9E%90%E4%B8%8E%E7%BB%9F%E8%AE%A1)

使用 `volantis v5.7.7`，注释掉busuanzi和leancloud的分析，开启twikoo评论，看到统计的dom已经是twikoo_visitors，但是没有数字，这样配置是错误的吗

**Comment by BeaCox** [comment]
注意到你站已经成功显示浏览量，现关闭此issue
