### ISSUE TITLE
不看就关掉吧

### ISSUE THREAD

**Issue by lovelyJason** [xaoxuu/hexo-theme-volantis#867]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [ ] 主题官网也存在这个问题。

### 复现步骤

我看了下你们仓库的代码历史， 用的cdn一开始是cdn.jsdelivr.net， 后来换成了gcore.jsdelivr.net

现在gcore.jsdelivr.net也挂了？我博客的字体， 图片也都挂了， 现在是换了哪个cdn啊？

![Snipaste_2023-04-21_16-10-58](https://user-images.githubusercontent.com/50656459/233580829-7d9fe024-7103-4ba4-84f4-d6efcd25a331.png)

全挂了啊

**Comment by Tikas** [comment]
其实并不是不看，而是目前没有什么好的解决 cdn 办法（主要是白嫖的方式），就没回复，因为回复了也不能解决问题。

如果不走 cdn ，可以在配置里把 cdn 关了，这样会加载站内的 css 等相关静态文件。

如果要走 cdn（白嫖方式），目前我能想到的是，可以尝试使用 https://www.cloudflare.com/ 里的 pages 部署一下 github 里的静态资源仓库，这样就能得到 cf 的静态链接，白嫖 cf 的全球加速。



<blockquote><img src="https://www.cloudflare.com/static/b30a57477bde900ba55c0b5f98c4e524/Cloudflare_default_OG_.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Cloudflare</div><div><strong><a href="https://www.cloudflare.com/">Cloudflare - The Web Performance & Security Company</a></strong></div><div>Here at Cloudflare, we make the Internet work the way it should. Offering CDN, DNS, DDoS protection and security, find out how we can help your site.</div></blockquote>
