### ISSUE TITLE
【问题】：手机版中的blogger组件显示问题

### ISSUE THREAD

**Issue by xingpingcn** [xaoxuu/hexo-theme-volantis#870]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

https://xingpingcn.github.io/

### 问题描述

![image](https://user-images.githubusercontent.com/117259690/233628233-ede93fb0-fcce-49db-9543-95257aabcc07.png)
没有以卡片形式显示

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by xaoxuu** [comment]
这个好像本来就设计成这个样子的

**Comment by xingpingcn** [comment]
> 这个好像本来就设计成这个样子的

文字没有反色

**Comment by u9521** [comment]
> > 这个好像本来就设计成这个样子的
> 
> 文字没有反色

在`xxx\themes\volantis\source\css\_style\_layout\sidebar.styl`
约line 180 - 200
```
    @media screen and (max-width: $device-tablet)
      box-shadow: none
      // 移除手机显示blogger背景限制
      //background: transparent !important
      // 移除手机端blogger顶部padding
      //margin-top: 2 * $gap
      //backdrop-filter: none
      //字体颜色改为text
      color: var(--color-text)
```
# 效果
模糊是自己加的
![Snipaste_2024-03-19_21-20-27day](https://github.com/volantis-x/hexo-theme-volantis/assets/63995396/17ccb2a2-f105-4260-9ab2-2ac296da9004)
![Snipaste_2024-03-19_21-21-44night](https://github.com/volantis-x/hexo-theme-volantis/assets/63995396/4b81f29b-7be5-4c92-9b58-c80bf988caa2)
