### ISSUE TITLE
【反馈】：手机模式下toc会被遮挡（以找到问题并修复）

### ISSUE THREAD

**Issue by xingpingcn** [xaoxuu/hexo-theme-volantis#873]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [X] 主题官网也存在这个问题。

### 复现步骤

已经找到了问题所在
改成.l_header {
    position: fixed;
    z-index: 10;}就没有问题
![image](https://user-images.githubusercontent.com/117259690/233852898-54783ff2-ac88-457e-bfba-29ef4e83ca9a.png)
![image](https://user-images.githubusercontent.com/117259690/233852900-f1c0cc53-90bc-47e3-b8e7-c6b137cac2e7.png)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>

**Comment by Tikas** [comment]
不应该哇，1000 是比 10 要大的，层次上来说应该是更上面，难道是浏览器开始只支持 三位数 的值？

**Comment by xingpingcn** [comment]
> 不应该哇，1000 是比 10 要大的，层次上来说应该是更上面，难道是浏览器开始只支持 三位数 的值？

原结构是这样的
![image](https://user-images.githubusercontent.com/117259690/233888774-2ec81e8e-6667-47fb-9d56-6a83c1217613.png)


应该就是设置成小于等于10的就可以，经测试，设置成11就会遮挡

btw，评论区怎么样显示raw字符，直接发就转义了

**Comment by Tikas** [comment]
哈哈，你可以使用波浪键上面的 【 ` 】，可以编辑我这条信息，查看 md 语法，建议有时间去学一下 markdown ，几分钟就能上手。

单个英文或小区域之间引用例子：

+ 前后使用 【 \` 】囊括：
  - 写法：\`\@xingpingcn\` 
  - 效果：`@xingpingcn` 
+ 前后不加 【 \` 】囊括：
  - 写法：@xingpingcn
  - 效果(github 会去 @ 这个ID，并且会有鼠标交互效果)：@xingpingcn

>当你编辑此信息时，你会看到 【 \\\` 】，这个【\】后面加的符号是转义输出的意思，就是原本是什么符号就显示出什么符号

而代码区域就使用三个【 \`\`\` 】前后囊括，示例：

\`\`\`
要描述的代码
\`\`\`

显示效果

```
要描述的代码
```

更进一步，可以在前面的三个【 \`\`\` 】写完，接着写上对应的代码语言，会有对应的高亮显示，示例：

\`\`\`css
要描述的代码
\`\`\`

显示效果：

```css
.toc {
    z-index:1001
}
.toc-wrapper {
    z-index:10
}
```
