### ISSUE TITLE
【问题】：Waline ReferenceError: Waline is not defined

### ISSUE THREAD

**Issue by ning0818** [xaoxuu/hexo-theme-volantis#892]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
##    (备注：issue#709 中并没有找到解决办法)
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [ ] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://www.yuanning0818.tk 中的任意一篇文章

### 问题描述

Waline ReferenceError: Waline is not defined
![image](https://github.com/volantis-x/hexo-theme-volantis/assets/117955401/b473c985-8a67-4443-a07f-e5bc4ee17188)

waline后端确定没问题，https://liuyan.yuanning0818.tk/

正常html引入也没问题，[https://cdn2.chuqis.com/gh/ning0818/hexoblog@main/source/waline.html](https://cdn2.chuqis.com/gh/ning0818/hexoblog@main/source/waline.html)
```
<head>
  <!-- ... -->
  <link
    rel="stylesheet"
    href="https://unpkg.com/@waline/client@v2/dist/waline.css"
  />
  <!-- ... -->
</head>
<body>
  <!-- ... -->
  <div id="waline"></div>
  <script type="module">
    import { init } from 'https://unpkg.com/@waline/client@v2/dist/waline.mjs';

    init({
      el: '#waline',
      serverURL: 'https://liuyan.yuanning0818.tk',
    });
  </script>
</body>
```

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

[```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```](https://cdn2.chuqis.com/gh/ning0818/hexoblog@main/themes/volantis/_config.yml)https://[cdn2.chuqis.com/gh/ning0818/hexoblog@main/themes/volantis/_config.yml](https://cdn2.chuqis.com/gh/ning0818/hexoblog@main/themes/volantis/_config.yml)

</p></details>


### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>
```
</details>
<h3>十分感谢！</h3>

**Comment by inkss** [comment]
主题去 jQuery，所以 `$` 会报错，后面的错误估计也是这个的后续影响
